### ISSUE TITLE
Consider adding this project to Bazel's CI.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#102]
If I read this documentation correctly:

https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md

It is possible to include our project in the list of projects tested by Bazel as they make changes. This would let them (and us) discover if any new release is about to break us.

See #101 for the motivation.

**Comment by tmatsuo** [comment]
Maybe I'll start this with a simple build on Ubuntu 18.04.

**Comment by tmatsuo** [comment]
https://github.com/bazelbuild/continuous-integration/issues/811

**Comment by tmatsuo** [comment]
Added, the dashboard is at:
https://buildkite.com/bazel/github-dot-com-googleapis-google-cloud-cpp-spanner

The builds are red now, but it is because the build is serving a purpose.

Closing this issue
