### ISSUE TITLE
tune default ConnectionOptions and SessionPoolOptions values.

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#1077]
We've selected default values for the members of `ConnectionOptions` and `SessionPoolOptions`; we should spend some time examining and possibly altering the chosen defaults.

This should also feed back into the cross-language design - ideally the defaults would be consistent across client libraries (which is what we're currently doing for c++)

**Comment by devjgm** [comment]
I'm thinking this may be closeable? Thoughts @mr-salty

**Comment by mr-salty** [comment]
Yeah, let's close this. The defaults in our library are the same as other client libraries and should be suitable for that purpose. Application authors may need to change them based on the characteristics of their application, hardware, spanner config, etc.
