### ISSUE TITLE
implement DataType integration tests for all the types in value.h

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#1096]
If this bug was already filed, I couldn't find it.

**Comment by coryan** [comment]
Can we define "all" a little better?  There is an infinite amount of data types possible in Cloud Spanner (I think, we have recursive types, right?).  So maybe we should just do the primitive types, arrays of primitive types, and something like `STRUCT<STRING, ARRAY<INT64>>` and `STRUCT<STRING, ARRAY<STRUCT<INT64, BOOL>>>`?

- [ ] `BOOL`
- [ ] `BYTES`
- [ ] `DATE`
- [ ] `FLOAT64`
- [ ] `INT64`
- [ ] `STRING`
- [ ] `TIMESTAMP`
- [ ] `ARRAY<BOOL>`
- [ ] `ARRAY<BYTES>`
- [ ] `ARRAY<DATE>`
- [ ] `ARRAY<FLOAT64>`
- [ ] `ARRAY<INT64>`
- [ ] `ARRAY<STRING>`
- [ ] `ARRAY<TIMESTAMP>`
- [ ] `STRUCT<STRING, ARRAY<INT64>>`
- [ ] `STRUCT<STRING, ARRAY<STRUCT<INT64, BOOL>>>`

**Comment by devjgm** [comment]
The spanner struct type ([docs](https://cloud.google.com/spanner/docs/data-types#struct-type)) cannot be used as a column type in a schema, so we cannot implement the last two integration tests that would write then read structs.

From the spanner docs:
> Note: STRUCT values can be constructed by SQL expressions, but are not supported as column types.

**Comment by coryan** [comment]
True, but we can use `STRUCT` as a parameter for a SQL statement, so maybe we could do something like:

```sql
INSERT INTO DataTypes
   SET StringValue = @param.StringValue
       ArrayInt64Value = @param.ArrayValue
       Id = @key
```

and pass `@param` as the equivalent of a `STRUCT<STRING, ARRAY<INT64>>` and then read back something like

```sql
SELECT (StringValue, ArrayInt64Value)
   FROM DataTypes
  WHERE Id = @key
```

The second case is more complicated, but still seems doable?
