### ISSUE TITLE
Timestamp type does not support full range documented by Spanner

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#1098]
Spanner [documents](https://cloud.google.com/spanner/docs/data-types#timestamp-type) the range for the `TIMESTAMP` type as

> 0001-01-01 00:00:00 to 9999-12-31 23:59:59.999999999 UTC.

The C++ type we use for `Timestamp` is 
https://github.com/googleapis/google-cloud-cpp-spanner/blob/0945decf6fe09daad3b7a1eac3e11b82fbab806c/google/cloud/spanner/timestamp.h#L37-L38

Which is 64-bits of nanoseconds, which will give us a range of +/- ~292 years.

We should figure out how we want to handle this. We probably want to support the full range of Spanner timestamps.

**Comment by devjgm** [comment]
Attn: @devbww who likes to think about these sorts of things :-)

**Comment by devjgm** [comment]
FWIW, one solution would be to take a dep on abseil (#566) then use `absl::int128` as the rep type in our Timestamp chrono alias. See also https://abseil.io/docs/cpp/guides/numeric

**Comment by devbww** [comment]
And also FWIW, I added a test case in Abseil that checks that
```
  std::chrono::time_point<std::chrono::system_clock,
                          std::chrono::duration<absl::int128, std::atto>>
```
works.  That is, that `absl::int128` supplies everything needed by `std::chrono`.

**Comment by coryan** [comment]
This is out of SLO for lack of updates I think.  We are waiting for a decision on taking a dependency on Abseil.

**Comment by devbww** [comment]
Sorry I didn't notice the SLO pings.

In any case, I have the new Timestamp class almost ready to go (I've been ignoring it for the past couple of weeks).  So I'll finish things off and get it out shortly.

**Comment by devjgm** [comment]
Any update on this issue?
