### ISSUE TITLE
Implement a wrapper for the Spanner.Commit RPC.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#11]
We want a wrapper for this RPC:

https://github.com/googleapis/googleapis/blob/fe77c6737fda6d3c43cc4666aff7d27be61fbfb6/google/spanner/v1/spanner.proto#L205

We do not know yet what the prototype for this wrapper should be, so that is probably the first step. The interesting bit is to implement mutations so we can insert, delete, and update rows.

**Comment by devjgm** [comment]
We will likely be moving this behavior to a "Transaction Runner" class.
