### ISSUE TITLE
Spanner install instructions use "$HOME/project", which I think does not exist

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#1131]
Looking at the debian buster install instructions [here](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/INSTALL.md#debian-10---buster), I see the use of strings like`cd $HOME/project`, but I see nowhere where that "project" directory gets created. From context I think it's supposed to contain the spanner source code, but I'm not certain and it's not clear from the doc.

We should clarify this.

FWIW, I found this while walking through the install instructions in a clean docker image and pasting in each command (as root). The following command didn't work and I think the lack of a "project" dir is why:

```
cd $HOME/project
cmake -H. -B/o
cmake --build /o -- -j "${NCPU:-4}"
cd /o
ctest -LE integration-tests --output-on-failure
cd $HOME/project
sudo cmake --build /o --target install
```

**Comment by remyabel** [comment]
The Dockerfiles use `/home/build/project`. `dockerfile2markdown` translates `/home/build` to `$HOME` which becomes `$HOME/project`. It doesn't look like the `INSTALL.md` preamble mentions obtaining `google-cloud-cpp-spanner` though. 

`cd /o` doesn't look right earlier. This will obviously navigate to a folder in the root directory, which makes sense for a Dockerfile, but not for the user's system.
