### ISSUE TITLE
Clean up vcpkg's buildtrees directory for saving disk space in Windows cmake builds

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp-spanner#1146]
When I tried to emulate the Kokoro Windows build on my own VM, I encountered disk space error. The vcpkg's `buildtrees` directory occupies around 9.5GB out of 10GB temporary disk. We should clean up unnecessary directories after the vcpkg build phase.

**Comment by coryan** [comment]
FWIW, I always create my Windows VMs with much larger disks:

https://github.com/googleapis/google-cloud-cpp-common/blob/master/doc/setup-development-environment.md#appendix-creating-a-windows-vm-using-google-compute-engine
