### ISSUE TITLE
Return type for *::ExecutionStats() may be too restrictive?

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1153]
The `ExecutionStats()` functions return `std::unordered_map<std::string, std::string>` to represent a `google.protobuf.Struct` proto:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/c28e495db521fe3407eb78c1cd9cde351e8e8ebf/google/cloud/spanner/results.h#L159

https://github.com/googleapis/google-cloud-cpp-spanner/blob/c28e495db521fe3407eb78c1cd9cde351e8e8ebf/google/cloud/spanner/results.h#L195

https://github.com/googleapis/googleapis/blob/2085a0d3c76180ee843cf2ecef2b94ca5266be31/google/spanner/v1/result_set.proto#L185-L194

I do not see any comments stating that the values for these statistics will *always* be strings. It seems possible that some are `INTEGER` types. Should we consider a different representation such as `spanner::Value`?

**Comment by devjgm** [comment]
From the Spanner folks, it sounds like the use of `google.protobuf.Struct` is a historical artifact about the `query_stats` field. Today and into the foreseeable future the returned stats will be strings. So therefore, I think we can leave our map of strings as the return type.

Thoughts?

**Comment by coryan** [comment]
SGTM.
