### ISSUE TITLE
implement resource-based routing

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#1181]
Spanner clients should determine the endpoint(s) to use by calling `InstanceAdmin.GetInstance` and consulting [`Instance.endpoint_uris`](https://github.com/googleapis/googleapis/blob/f6808ff4e8b966cd571e99279d4a2780ed97dff2/google/spanner/admin/instance/v1/spanner_instance_admin.proto#L401-L409) in the response, falling back to the default endpoint if no useable endpoints are returned.

```
  // Output only. The endpoint URIs based on the instance config.
  // For example, instances located in a specific cloud region (or multi region)
  // such as nam3, would have a nam3 specific endpoint URI.
  // This URI is to be used implictly by SDK clients, with fallback to default
  // URI. These endpoints are intended to optimize the network routing between
  // the client and the instance's serving resources.
  // If multiple endpoints are present, client may establish connections using
  // any of the given URIs.
  repeated string endpoint_uris = 8;
```

Since the backends may not yet support this, we may need to make it optional (the [go client uses an environment variable](https://github.com/googleapis/google-cloud-go/blob/cca68827d1700019ecd6a99ce0c2710443bd5612/spanner/client.go#L195)) for this purpose. However, as noted previously, the client must already fall back to the default endpoint so perhaps making it optional is not necessary.

**Comment by mr-salty** [comment]
One open question/TODO: if multiple `endpoint_uris` are returned, and the client is configured to use multiple gRPC channels, should it pick one endpoint for all channels, or distribute channels across endpoints?

**Comment by mr-salty** [comment]
per the cloud spanner team, all clients should allow the feature to be disabled by environment variable (`GOOGLE_CLOUD_SPANNER_ENABLE_RESOURCE_BASED_ROUTING=false`) for troubleshooting (and as discussed above we may want to default it to `false` until feature launch)

**Comment by coryan** [comment]
FWIW, we need new versions of the spanner `.proto` files to implement this, and when we get those files the generated .cc files stop compiling on Windows due to protocolbuffers/protobuf#7076.

I filed #1230 to remind us that all those updates are needed before we can implement this code.

**Comment by devbww** [comment]
#1253 gave us the new versions of the spanner `.proto` files.

**Comment by devjgm** [comment]
Due to "reasons", we're dropping this.
