### ISSUE TITLE
Consider removing checksums from release tarballs

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#1187]
(This issue applies to all of our repos, but I'm filing the issue only in this repo.)

This discussion started offline, but I'm moving it into an issue so we don't lose track of it.

The question is whether there's any meaningful reason for us to continue publishing file checksums for each release's `.tar.gz` and `.zip` assets along with the Release Notes. See https://github.com/googleapis/google-cloud-cpp-spanner/releases. Or if we should simply stop publishing these checksums.

### Reasons to KEEP publishing the checksums

* If a user downloads our released tarball, they may have disk or memory corruption that they could detect if they also verified the checksum of the downloaded file.

### Reasons to STOP publishing checksums

* The source tarballs are downloaded over HTTPS or SSH, which should pretty well guarantee there's no corruption during transmission.

* Our checksums are not crypographically signed, so if we're concerned about malicious attackers, they could easily attack our published plain-text checksums as well. In other words, our checksums are only as safe/secure as the tarballs they sit next to.

* It's a a mild PITA to maintain these checksums as described in the [cutting-a-release](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/doc/cutting-a-release.md#create-pre-release-for-review) doc. We could script and automate this, but that also takes effort to do and maintain.

* Few other GH projects publish checksums for source tarball releases. Some projects which do NOT publish checksums: Abseil, Facebook Folly, Microsoft vcpkg, Bazel, google-cloud-java. I'm sure there's more, but those were literally the *first* projects I thought to check and none of them publish checksums.

---

Are there other reasons for/against that I missed? Or have I failed to fairly capture the reasons above?

**Comment by devjgm** [comment]
FTR, I do not see the benefit to publishing unsigned checksums as we do now. My vote is to simplify our lives and get rid of them.

**Comment by remyabel** [comment]
> The source tarballs are downloaded over HTTPS or SSH, which should pretty well guarantee there's no corruption during transmission.

This covers integrity but not authenticity. I think instead of publishing the checksums you could simply sign each release with a GPG key then publish the fingerprint of the signing key. This doesn't introduce any additional complexity and can be automated.

**Comment by devjgm** [comment]
While signing would be better, it doesn't come without cost. There's management of the private key, etc. We could certainly consider that as a *separate* possible option. But for now -- when we don't sign -- should we bother keeping the existing (unsigned) checksums are not.

**Comment by coryan** [comment]
For the record, I am Okay if we remove these.

**Comment by devjgm** [comment]
An offline vote resulted in:
4 votes to remove the checksums
2 vote to keep them

**Comment by devjgm** [comment]
This is almost done. I'm finished updating all of our release instructions to no longer include adding the checksums to the releases page.

## One final question
Do we want to keep or remove the checksums on all of our existing releases?

Removing them seems fine to me. I'd do it if we want to go that way.

Leaving them seems fine too, though the inconsistency between releases would be visible to customers.

Any opinions?

**Comment by devjgm** [comment]
I think we roughly decided offline to leave the existing release checksums there. If we change our mind, we can remove them later, or file a new issue.

Therefore, this issue is finished.
