### ISSUE TITLE
Consider moving release notes to CHANGELOG.md

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#1205]
(This bug applies to all of our repos)

We currently include release notes for each release in each product's `README.md` file. This will cause the README.md file to grow without end. Since the README.md file is displayed automatically as the main landing page for users, I think it would be good to keep this file as clean, clear, and simple as possible.

Therefore, I propose a change to our release process where by we move all of our existing release notes out of README.md and into a new file, I'll propose `CHANGELOG.md` (which appears to be somewhat common). 

Pros of moving release notes to CHANGELOG.md:
- README.md will become simpler
- README.md will not grow longer with each release

Cons:
- ??? None?

Questions:
- Is there any opposition to this suggestion? Are there reasons why we should keep the release notes in the README.md file?

- What's the right name for the new file? `CHANGELOG.md`? `RELEASE_NOTES.md`? Something else?
-

**Comment by coryan** [comment]
SGTM.

**Comment by coryan** [comment]
I think we should consider filing these in `google-cloud-cpp` instead btw.

**Comment by devjgm** [comment]
Makes sense. Moved this issue there.
