### ISSUE TITLE
Move googleapis.BUILD to googleapis/googleapis/**/BUILD

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1210]
The source of truth for these files is inside Google, so we need to make the changes there.

**Comment by devjgm** [comment]
This is done. In -cpp, our https://github.com/googleapis/google-cloud-cpp/blob/master/bazel/googleapis.BUILD file is fairly minimal. We use the build rules directly form googleapis/googleapis.
