### ISSUE TITLE
Consider removing tests for install instructions

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1216]
The instructions to install the library (in `INSTALL.md`) include the dependencies necessary to run the tests.  While it is nice to run the tests for our own peace of mind, it makes the installation more difficult for our users, we can remove 2 steps from the installation instructions if we remove the tests.

We do need to test that the installation works, i.e., that one can create a working program from the installed libraries. But I am not sure running the unit and integration tests helps all that much.

**Comment by devjgm** [comment]
FWIW, I vote for simplifying the installation instructions as much as possible. Likely, the only folks who need to run *our* tests will be folks who are developing in our repo, and they'll be working from a git clone, not installed binaries.
