### ISSUE TITLE
Upgrade builds to use protobuf-3.11.3

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1230]
This will be the first version with the fixes for protocolbuffers/protobuf#7076, which we need to compile the latest version of googleapis (via cpp-cmakefiles >= v0.4.1) which contains the support for resource-based routing.

**Comment by coryan** [comment]
Blocked on waiting for the Protocol Buffers release.

**Comment by devbww** [comment]
We now have protobuf-3.11.3, so I'll repurpose this for the upgrade to cpp-cmakefiles v0.4.1.

**Comment by devbww** [comment]
@coryan ... should I upgrade googleapis/cpp-cmakefiles to the latest googleapis/googleapis first?

**Comment by coryan** [comment]
I do not know.  If all the proto changes you need are in 0.4.1, then probably not, because why do more work?  Otherwise, then yes, you have to create 0.4.2 or 0.5.0 (I have been increasing the minor number for new libraries, the minor for just tweaks to the protos).

**Comment by coryan** [comment]
I just remembered something. The Windows+CMake build is still on protobuf-3.11.2, and won't compile with 0.4.1 (or any newer protos).

**Comment by devbww** [comment]
It appears that everything I need (for #1181) is indeed already in cpp-cmakefiles v0.4.1.

And nothing that anyone else needs has yet landed in googleapis/googleapis.

So, I'll skip the googleapis/googleapis update.

**Comment by devbww** [comment]
> I just remembered something. The Windows+CMake build is still on protobuf-3.11.2, and won't compile with 0.4.1 (or any newer protos).

This is a vcpkg thing?  Or, more specifically, what might I be able to do to get Windows+CMake up to protobuf-3.11.3?

**Comment by coryan** [comment]
> > I just remembered something. The Windows+CMake build is still on protobuf-3.11.2, and won't compile with 0.4.1 (or any newer protos).
> 
> This is a vcpkg thing?

Yes. It should be a matter of hours (or at most days) for Microsoft/vcpkg#9889 to be merged though.

> Or, more specifically, what might I be able to do to get Windows+CMake up to protobuf-3.11.3?

Wait for that PR to merge or the overlay crazy dance.

**Comment by devbww** [comment]
Excellent.  I can wait.  Thanks.

**Comment by devbww** [comment]
microsoft/vcpkg#9889 is merged.  Yay.

So I'll now move forward on the upgrade to cpp-cmakefiles v0.4.1.

**Comment by devbww** [comment]
Fixed by #1247 and #1253.
