### ISSUE TITLE
Version numbers in `INSTALL.md` and `spanner-main.dox` are not updated during release

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#1288]
The current version of [`INSTALL.md`](https://github.com/googleapis/google-cloud-cpp-spanner/blob/a120e85574a099683642e46d1804e2b68f69c6f3/INSTALL.md) has out of date version information (the current release is 0.8.0 but it says 0.7.0).

We will need to update this when [cutting a release](https://github.com/googleapis/google-cloud-cpp/blob/master/doc/cutting-a-release.md), ideally automatically.  Note that the version number for the `-spanner` release as well as `common` are hard-coded in multiple places in [`generate-install.sh`](https://github.com/googleapis/google-cloud-cpp-spanner/blob/45961b890515d5d1476c85ced2c9c52e4e0040cd/ci/test-readme/generate-install.sh).

Note that we will want to update this in the release branch as well as in HEAD.

**Comment by mr-salty** [comment]
I also noticed a comment referencing 0.7.0 in [`ci/test-install/WORKSPACE`](https://github.com/googleapis/google-cloud-cpp-spanner/blob/45961b890515d5d1476c85ced2c9c52e4e0040cd/ci/test-install/WORKSPACE#L27-L28l)

**Comment by mr-salty** [comment]
[`spanner-main.dox`](https://github.com/googleapis/google-cloud-cpp-spanner/blob/6dd199b20053f804a17efb4d4c9fd47628ad11ba/google/cloud/spanner/doc/spanner-main.dox#L114-L118) also refers to `0.7.0` (this is published on [github.io](https://googleapis.github.io/google-cloud-cpp-spanner/latest/)).

It also has this [obsolete instruction](https://github.com/googleapis/google-cloud-cpp-spanner/blob/6dd199b20053f804a17efb4d4c9fd47628ad11ba/google/cloud/spanner/doc/spanner-main.dox#L101-L104):

> As we do not currently have releases of `google-cloud-cpp-spanner` you need to
select the SHA-1 of the [commit](https://github.com/googleapis/google-cloud-cpp-spanner/commits/master) you want to use.

**Comment by mr-salty** [comment]
There is also a lot of commonality between `INSTALL.md` and `spanner-main.dox`, perhaps we should "refactor" (can the former just refer to the latter?)

**Comment by coryan** [comment]
> There is also a lot of commonality between `INSTALL.md` and `spanner-main.dox`, perhaps we should "refactor" (can the former just refer to the latter?)

OTOH, I have been told that it is preferable to have all the information in a single page vs. forcing the user to link through many pages to find what they need, particularly for "landing" or "quick start pages".

**Comment by devjgm** [comment]
I believe this has been/will be taken care of when Spanner moves to -cpp. In that world, there is no separate -common version to update. And the release instructions do now talk about updating all the relevant version numbers (and if we miss one, we'll fix it in that repo).
