### ISSUE TITLE
Remove dependency on bigtable_client.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#129]
We needed a function (`internal::MakeStatusFromGrpcError`) in the bigtable_client library, so I added it as a dependency. We should refactor the function to a new library. Note that the function cannot be moved to `google_cloud_cpp_common` as it depends on gRPC and we do not want Cloud Storage to depend on gRPC.

**Comment by remyabel** [comment]
[WIP branch](https://github.com/remyabel/google-cloud-cpp-spanner/tree/remove-bigtable-dependency)

The `clang-tidy` build now passes. The `cmake-super` build *does not* pass. For some reason, this integration test is failing:

```
[ RUN      ] DatabaseAdminClient.DatabaseBasicCRUD
/v/google/cloud/spanner/integration_tests/database_admin_integration_test.cc:47: Failure
Value of: project_id.empty()
  Actual: true
Expected: false
[  FAILED  ] DatabaseAdminClient.DatabaseBasicCRUD (0 ms)
[----------] 1 test from DatabaseAdminClient (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DatabaseAdminClient.DatabaseBasicCRUD

 1 FAILED TEST
```

**Comment by coryan** [comment]
The integration tests for Spanner can only run against production, and they need to have a number of environment variables set for them to run (`GOOGLE_CLOUD_PROJECT`

**Comment by coryan** [comment]
Sorry, I don't know what I clicked that closed this issue.

**Comment by remyabel** [comment]
> Are you running these manually? Typically the integration tests are disabled except for the integration and coverage builds.

No I am not. I'm running it with `./ci/kokoro/docker/build.sh` and the tests fail for the WIP branch, so either I'm doing something wrong or it pulled in a `google-cloud-cpp` update that breaks something.

**Comment by remyabel** [comment]
My bad. I misunderstood. The `cmake-super` build *does not* exclude the integration tests.

**Comment by coryan** [comment]
We are not running that build in the CI system, we should fix both these issues. Thanks for bringing it up.
