### ISSUE TITLE
Separate INSTALL instructions by expected user

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1295]
The current instructions have three different audiences, with almost no overlap:

- [ ] Users that want to compile and use `google-cloud-cpp-spanner` using Bazel.
- [ ] Users that want to compile and use `google-cloud-cpp-spanner` using CMake.
- [ ] Package maintainers that want to to compile and install `google-cloud-cpp-spanner` for other users.

We should consider splitting this into three documents.

**Comment by devjgm** [comment]
Based on recent discussions this morning, I think this issue is now subsumed by #1310, so closing this one.
