### ISSUE TITLE
Create complete hello-world directory / repository to compile with Bazel and/or CMake

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1299]
We should have a directory and/or repository that users can copy and start coding from a simple "hello world" program. It should support both CMake and Bazel.

**Comment by devjgm** [comment]
I'm thinking this is done now? https://github.com/googleapis/google-cloud-cpp-spanner/tree/master/quickstart

**Comment by coryan** [comment]
Yes, fixed by #1318
