### ISSUE TITLE
Implement GAPIC-like SpannerStub scaffolding

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#13]
We will need a `spanner::SpannerClient` and `spanner::SpannerStub` inspired by the description in  go/actools-cpp-gapic-stub, these would be empty classes where we will later add all the RPCs.

At the end of this task we will have:

- [ ] A `spanner::SpannerClient` class with more or less this body:

```C++
class SpannerClient {
  public:
    // Create the default SpannerStub().
    SpannerClient(
        std::string project_id, std::string instance_id, std::string database_id);

   // TODO(...) - need a constructor with non-default ClientOptions, such as credentials,
   // connection pool sizes, service endpoint, etc.

    std::string const& project_id() const;
    std::string const& instance_id() const;
    std::string const& database_id() const;
    std::string /* const& ? */ instance_name() const;
    std::string /* const& ? */ database_name() const;

    // TODO:
    // ReadStream Read(...);

  private:
};
```

- [ ] A `spanner::SpannerStub` class with more or less this body:

```C++
class SpannerStub {
  public:
    SpannerStub(
        std::string project_id, std::string instance_id, std::string database_id,
        std::shared_ptr<grpc::Credentials> credentials);

    std::string const& project_id() const;
    std::string const& instance_id() const;
    std::string const& database_id() const;
    std::string /* const& ? */ instance_name() const;
    std::string /* const& ? */ database_name() const;

    // TODO(...) - thin wrappers around the gRPC-generated functions:
    // grpc::Status Read(grpc::ClientContext*, ...Request const&, ...Response* );

  private:
    // Initially just have one channel, and one stub:
    std::shared_ptr<grpc::Channel> channel_;
    // TODO(...) - this may not be the right type, going from memory...
    std::unique_ptr<google::spanner::v1::Spanner::Stub> stub_;
};
```

**Comment by mr-salty** [comment]
We should be careful with the name `SpannerClient` since we already have a higher-level `[google::cloud::]spanner::Client`. I also opened #26 to track that separately.

**Comment by mr-salty** [comment]
From our discussion: the classes we add to do this should be roughly analogous to what GAPIC will eventually generate; they should include testing support (mock/fake) as well as the ability to make gRPC calls to the real Spanner service.

**Comment by devjgm** [comment]
This PR is confusing to me. I think we need two things:

1. `spanner::Client`, which is captured in https://github.com/googleapis/google-cloud-cpp-spanner/issues/29 -- this is the class that our users will directly use.

2. a "SpannerStub" class, that wraps the gRPC API, and provides for us what gapic would have provided. Since this PR has some history and somewhat covers both cases, I think we should split this latter thing out into a separate issue to make that clear. Then close this issue.... I'm going to do that.  Done: https://github.com/googleapis/google-cloud-cpp-spanner/issues/61
