### ISSUE TITLE
docs: Create cross links to google-cloud-cpp-common

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp-spanner#1301]
An example:
If the `google::cloud::future` in the following page becomes a link, that's great.

https://googleapis.dev/cpp/google-cloud-spanner/latest/classgoogle_1_1cloud_1_1spanner_1_1v0_1_1DatabaseAdminClient.html#af19c5d53e7f32bba140cd74fdf4dfe05

The `google::cloud::future` doc:
https://googleapis.dev/cpp/google-cloud-common/latest/classgoogle_1_1cloud_1_1v0_1_1future.html

**Comment by tmatsuo** [comment]
It's partially working. For example, the following page:
https://googleapis.dev/cpp/google-cloud-spanner/master/database__admin__client_8h_source.html

has some links to `future.h` and `status_or.h`.

However, other pages like this:
https://googleapis.dev/cpp/google-cloud-spanner/master/classgoogle_1_1cloud_1_1spanner_1_1v0_1_1DatabaseAdminClient.html
don't have links to future or status_or.

**Comment by tmatsuo** [comment]
Maybe related, maybe not:
https://github.com/doxygen/doxygen/issues/4168

It might be worthwhile to try the newest version of doxygen.

**Comment by tmatsuo** [comment]
Unfortunately I tried doxygen 1.8.17, but it doesn't give much difference.

**Comment by tmatsuo** [comment]
The generated tag file (`cloud.tag`) contains entries like this:

```
  <compound kind="file">
    <name>status_or.h</name>
    <path>/v/google/cloud/</path>
    <filename>status__or_8h</filename>
    <includes id="status_8h" name="status.h" local="yes" imported="no">google/cloud/status.h</includes>
    <class kind="class">google::cloud::v0::StatusOr</class>
    <namespace>google</namespace>
    <namespace>google::cloud</namespace>
    <namespace>google::cloud::v0</namespace>
    <member>...</member>
  </compound>
```

It might be because the class name is a fully qualified (including the inline version namespace) class name, while the filename is just the base name with nested namespaces around it, or probably it's identified with the `includes` tag above.

**Comment by coryan** [comment]
Note that the generated Doxygen file for me (in `$BINARY_DIR/google/cloud/spanner/Doxyfile.doxygen-docs`) reads:

```
... ... ...
... ...
PREDEFINED             = SPANNER_CLIENT_NS=v0
EXPAND_AS_DEFINED      = 
SKIP_FUNCTION_MACROS   = YES
TAGFILES               = /Users/coryan/span-develop/cmake-build-debug/cloud.tag=https://googleapis.dev/cpp/google-cloud-common/master/
GENERATE_TAGFILE       = /Users/coryan/span-develop/cmake-build-debug/google/cloud/spanner/.tag
... ... ...
... ...
```

Seems like we need to add `GOOGLE_CLOUD_CPP_NS=v0` to this line:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/00ca369b7acd29022ff98ea2c4342ccd68eb2c6b/cmake/EnableDoxygen.cmake#L66

**Comment by tmatsuo** [comment]
Thanks, unfortunately it doesn't seem to work either. I'm running out of my options. I'd free this issue from myself for now so that others can try something else.

**Comment by devjgm** [comment]
This may be obsolete now since we're moving to a monorepo in -cpp, and all the common and product code will live in the same repo. We may still have issues with doxygen choking on inline namespaces, but that's a doxygen issue, not an issue of us cross linking.

Closing. If I'm mistaken about this, we can re-open.
