### ISSUE TITLE
Create a page describing the environment variables for the library.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1306]
We have quite a few of them, for example:

- `GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes` turns on logging in the library, basically the library always "logs" but the logging infrastructure has no backend to actually print anything until the application sets a backend or they set this environment variable.

- `GOOGLE_CLOUD_CPP_ENABLE_TRACING=rpc` turns on tracing for all gRPC calls, the library injects an additional `Stub` decorator that prints each gRPC request and response.

- `GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT` changes the default endpoint (`spanner.googleapis.com`) for the spanner client library, useful for debugging.

- `SPANNER_EMULATOR_HOST` changes the default endpoints and uses insecure credentials.

- `GOOGLE_CLOUD_PROJECT` is used in examples and integration tests to configure the GCP project.

- `GOOGLE_CLOUD_CPP_SPANNER_INSTANCE` is used in examples and integration tests to, well, configure the spanner instance.

There are a few others used to control the integration tests that probably should go undocumented.

**Comment by devbww** [comment]
> `GOOGLE_CLOUD_CPP_ENABLE_TRACING=rpc` turns on tracing for all gRPC calls

We also look at `GOOGLE_CLOUD_CPP_ENABLE_TRACING=rpc-streams` for `Read()`, `ExecuteQuery()`, and `ProfileQuery()`.

**Comment by devjgm** [comment]
Is there a reason that `GOOGLE_CLOUD_CPP_ENABLE_TRACING=rpc-streams` is using "rpc-streams" rather than just "rpc"? Is this difference desirable? I'm wondering if we can just simplify this so that `GOOGLE_CLOUD_CPP_ENABLE_TRACING=rpc` enables tracing of *all* RPCs (as its name may seem to imply).

**Comment by coryan** [comment]
> Is there a reason that `GOOGLE_CLOUD_CPP_ENABLE_TRACING=rpc-streams` is using "rpc-streams" rather than just "rpc"? Is this difference desirable?

I think so, but I can be convinced otherwise: you get *lots* of data when `rpc-streams` is turned on, but a lot less when it is not.  

> I'm wondering if we can just simplify this so that `GOOGLE_CLOUD_CPP_ENABLE_TRACING=rpc` enables tracing of _all_ RPCs (as its name may seem to imply).

My opinion is so changeable in this that *if* somebody sends a PR I would gladly approve, we can change it back later if we get any user feedback.

**Comment by devjgm** [comment]
I'm just trying to figure out how to explain the difference to users. Use "rpc" if you want ???? And use "rpc-streams" if you want ???

OK, I'll try to document this.
