### ISSUE TITLE
Do spanner::Value of type struct have correct representation when fields are NULL?

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp-spanner#1347]
Another way to phrase the issue is, in the case of structs, should there be an equal number of type and value fields regardless of the presence of any NULL values?

Currently, when we invoke 
```
MakeNullValue<std::tuple<bool, std::int64_t>>(), "()");
```
we create a Value with 2 types (bool, int) but with 0 values.

**Comment by devjgm** [comment]
That seems correct to me. Can you say more about why you think it's wrong?

**Comment by devjgm** [comment]
To be clear, we shouldn't have 0 values, we should have an explicit null value. See this code:
https://github.com/googleapis/google-cloud-cpp-spanner/blob/002096bee7dc1daece5c6abec4ef13aa39436389/google/cloud/spanner/value.h#L451

Is that what you see?

**Comment by devjgm** [comment]
FTR, I think

```cc
MakeNullValue<std::tuple<bool, std::int64_t>>()
```

Should render as "NULL", not "()"

**Comment by devjgm** [comment]
After some discussions offline and in https://github.com/googleapis/google-cloud-cpp-spanner/pull/1336, I think the answer is that `Value` does currently represent structs correct whether they're NULL or they have NULL members.
