### ISSUE TITLE
Could not build samples on macOS

### ISSUE THREAD

**Issue by mmmarklu** [googleapis/google-cloud-cpp-spanner#1363]
Answering these questions before submitting your bug report will help us give you a quicker answer. Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp-spanner` project?

yes 

### What version of `google-cloud-cpp-spanner` are you using?

master                        88adb644126241cb95a8563a8eeae1c322653104

### What compiler and version are you using?

bazel 2.2.0

### What operating system and version are you using?

macOS Catalina

### What were you trying to do?

bazel build //google/cloud/spanner/samples:samples

as described in 

https://github.com/googleapis/google-cloud-cpp-spanner/tree/master/google/cloud/spanner/samples

### What did you expect to see?

BUILD Succeeded

### What did you see instead?

ERROR: /private/var/tmp/_bazel_marklu/33b2260bca2f167283c066e69dc97a85/external/com_google_protobuf/BUILD:334:1: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1): cc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_marklu/33b2260bca2f167283c066e69dc97a85/sandbox/darwin-sandbox/101/execroot/com_github_googleapis_google_cloud_cpp_spanner && \
  exec env - \
    PATH=/Users/marklu/Downloads/google-cloud-sdk/bin:/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin/:/Users/marklu/NVPACK/android-sdk-macosx/tools:/Users/marklu/NVPACK/android-sdk-macosx/platform-tools:/Users/marklu/NVPACK/android-sdk-macosx/build-tools:/Users/marklu/NVPACK/android-sdk-macosx/extras/android/support:/Users/marklu/NVPACK/android-ndk-r12b:/Users/marklu/NVPACK/apache-ant-1.8.2/bin:/Users/marklu/NVPACK/gradle-2.9/bin:/Users/marklu/bin \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/csharp_source_generator_base.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/csharp_source_generator_base.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/host/bin/external/zlib -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/host/bin/external/zlib -g0 -g0 -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -Wno-deprecated-declarations -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/compiler/csharp/csharp_source_generator_base.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/csharp_source_generator_base.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox cc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_marklu/33b2260bca2f167283c066e69dc97a85/sandbox/darwin-sandbox/101/execroot/com_github_googleapis_google_cloud_cpp_spanner && \
  exec env - \
    PATH=/Users/marklu/Downloads/google-cloud-sdk/bin:/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin/:/Users/marklu/NVPACK/android-sdk-macosx/tools:/Users/marklu/NVPACK/android-sdk-macosx/platform-tools:/Users/marklu/NVPACK/android-sdk-macosx/build-tools:/Users/marklu/NVPACK/android-sdk-macosx/extras/android/support:/Users/marklu/NVPACK/android-ndk-r12b:/Users/marklu/NVPACK/apache-ant-1.8.2/bin:/Users/marklu/NVPACK/gradle-2.9/bin:/Users/marklu/bin \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/csharp_source_generator_base.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/csharp_source_generator_base.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/host/bin/external/zlib -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/host/bin/external/zlib -g0 -g0 -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -Wno-deprecated-declarations -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/compiler/csharp/csharp_source_generator_base.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/csharp_source_generator_base.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
clang: error: unknown argument: '-fno-canonical-system-headers'

### Anything else you would like us to know?

I think I downloaded and set env var for roots.pem correctly.

**Comment by coryan** [comment]
Is it possible that you have the Android SDK installed and Bazel is picking up that SDK instead of the native development one (say xcode?)

**Comment by devjgm** [comment]
@mmmarklu are you still seeing a problem or should we close this?

**Comment by coryan** [comment]
@mmmarklu please feel free to reopen if this is still an issue.
