### ISSUE TITLE
[Flake] Code coverage build fails while running the samples

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1376]
One of the builds failed with the following error:

```
Error in non-idempotent operation RestoreDatabase: Cannot restore database (projects/cloud-cpp-testing-resources/instances/test-instance-0/databases/db-1zrczt-uwik-l4r2thqk1v9zrgw) because the maximum number of pending restores (1) for the instance (projects/cloud-cpp-testing-resources/instances/test-instance-0) has been reached. Please retry the operation once the pending restores complete. [FAILED_PRECONDITION]
```

https://source.cloud.google.com/results/invocations/d72bc156-f625-4ea3-b41c-64711458fce3

If I am reading the error message right, we cannot have two builds run that test simultaneously on the same instance.  This looks like a recipe for flakiness.

**Comment by coryan** [comment]
Another one, note that this is a different instance:

```
Error in non-idempotent operation RestoreDatabase: Cannot restore database (projects/cloud-cpp-testing-resources/instances/test-instance-6/databases/db-x0j3k4aw00ih_wegh2n9fau2-zk) because the maximum number of pending restores (1) for the instance (projects/cloud-cpp-testing-resources/instances/test-instance-6) has been reached. Please retry the operation once the pending restores complete. [FAILED_PRECONDITION]
```

https://source.cloud.google.com/results/invocations/662908df-1210-4ea5-afbe-931c45255740/targets

**Comment by tmatsuo** [comment]
Oh I see, we should create a new instance with a random name.

**Comment by coryan** [comment]
> Oh I see, we should create a new instance with a random name.

That might work, with a few caveats: we might run out of instance quota (we are pretty close I think), so removing stale instances created for this purpose becomes super important, and that can take a long time, right?

Anyway, if you have a PR that improves things please send it.

**Comment by tmatsuo** [comment]
We can put the backup related tests into the existing instance crud tests block. PR is coming soon.
