### ISSUE TITLE
Consider escaping STRING value data when printing them via Value::op<<

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#1380]
I'm sorry I missed the bit in the PR description.  I still dissent though.  `std::string` also doesn't wrap its output with quotes.  Rendering a `STRING` value is fundamentally different to printing a string of characters.  But, so be it.

_Originally posted by @devbww in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0Mzg4MDU1ODgz/pull_requests/unread_timeline_

**Comment by coryan** [comment]
FWIW, I do not think we should escape the *contents* of a `STRING`.  Spanner strings are UTF-8:

https://cloud.google.com/spanner/docs/data-definition-language#scalars

"Cloud Spanner requires Unicode strings to be UTF-8 encoded on receipt at the server."

We want these strings to print nicely if the user has UTF-8 encoded data. that is we want the output from something like this:

```console
$ gcloud spanner databases execute-sql --instance="${GOOGLE_CLOUD_CPP_SPANNER_INSTANCE}" "${GOOGLE_CLOUD_CPP_SPANNER_DATABASE}" --sql='select * from greetings'
text
Hello world
Hello world, Καλημέρα κόσμε, コンニチハ
Καλημέρα κόσμε
コンニチハ
```

to look good from C++:

```console
$ ./cmake-build-debug/google/cloud/spanner/samples/samples get-greetings-as-string "${GOOGLE_CLOUD_PROJECT}" "${GOOGLE_CLOUD_CPP_SPANNER_INSTANCE}" "${GOOGLE_CLOUD_CPP_SPANNER_DATABASE}"
text
Hello world
Hello world, Καλημέρα κόσμε, コンニチハ
Καλημέρα κόσμε
コンニチハ
```

**Comment by coryan** [comment]
As to the rendering with or without quotes: I am not sure there is a "Right Way":tm: to print these things. I would *prefer* if the output had as few decorations as possible, and that the intuitive (see below) way to print `SELECT *` worked more or less the same as the intuitive way to print `SELECT column1, column2, column3`.

```C++
void GetGreetings(google::cloud::spanner::Client client) {
  namespace spanner = ::google::cloud::spanner;
  auto rows =
      client.ExecuteQuery(spanner::SqlStatement("SELECT * FROM Greetings"));
  bool first_row = true;
  for (auto const& row : rows) {
    if (first_row) {
      char const* sep = "";
      auto const& columns = row.value().columns();
      for (auto& c : columns) {
        std::cout << sep << c;
        sep = "\t";
      }
      std::cout << "\n";
      first_row = false;
    }
    auto const& values = row.value().values();
    char const* sep = "";
    for (auto& v : values) {
      std::cout << sep << v;
      sep = "\t";
    }
    std::cout << "\n";
  }
}
```

**Comment by devbww** [comment]
> `std::cout << sep << v;`

When considering, be careful to distinguish this from `std::cout << sep << v.get<std::string>();`.

**Comment by devjgm** [comment]
> > `std::cout << sep << v;`
> 
> When considering, be careful to distinguish this from `std::cout << sep << v.get<std::string>();`.

Can you clarify *why* we want to distinguish those cases? I ask because my first reaction is that those two cases should print exactly the same. But I think you're suggesting that we might want to treat them differently.

**Comment by devjgm** [comment]
This issue is now about two things:

1. Whether or not to escape STRING data
2. Whether to surround STRING data with double quotes

I'm going to split the second issue out into a separate issue https://github.com/googleapis/google-cloud-cpp-spanner/issues/1391, where we can discuss that one.

For the first issue, I think given Carlos's example and the observation that Spanner STRINGs must be valid UTF-8, suggests that we should not escape non-printable bytes, because that would break the UTF-8 rendering.

So I'm going to close this issue saying that we considered it and decided not to. If someone thinks this is the wrong conclusion and has more data to present in favor of escaping STRING data, please feel free to re-open this issue so we can discuss.

Regarding the quoting, we'll continue that discussion in #1391
