### ISSUE TITLE
Write a test to compare StreamingRead() vs. Read().

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#14]
Write a small test that performs a lot of `Read()` calls getting a single row and compare the performance of that approach vs. `StreamingRead()`.

**Comment by devbww** [comment]
Carlos wrote:
> My guess is when reading a single row (a common case I think), or a small number of rows (less common) the non-streaming version is more efficient.

The thought during the local discussion was that a `PartialResultSet` without a `resume_token` _"must be"_ just as efficient as a `ResultSet`, the corollary being that it didn't matter if you did a `Read()` or a `StreamingRead()` when everything came back in one response.  And given that large responses probably need a `StreamingRead()`, the idea was to only use `StreamingRead()`.

However, given the existence of non-streaming `Read()`, something in that logic sounds funny.  I'm not sure that writing the suggested small test will indicate what that is though.  Perhaps we just need to be told.

> Also, when we go and implement the ExecuteSql() thing, UPDATE and INSERTS return a single element, it also seems wasteful to setup a stream to just get the one element for them.

I'm not sure what _"stream"_ you're referring to there, but if the result of `Read()` or `ExecuteSql()` is always an iteration of `Row`s, yet the caller knows there will be exactly `N` rows in the result and wants to deal with them en masse, then perhaps they just build there own `vector` from the iteration first.

**Comment by coryan** [comment]
> I'm not sure what _"stream"_ you're referring to there,

The RPC for streaming read is a streaming RPC:

https://github.com/googleapis/googleapis/blob/f86c9531dc49d41267e2117ece1ea29840f15ce3/google/spanner/v1/spanner.proto#L178

vs. the RPC for a regular read, which is a simple unary RPC:

https://github.com/googleapis/googleapis/blob/f86c9531dc49d41267e2117ece1ea29840f15ce3/google/spanner/v1/spanner.proto#L166

Making a streaming RPC is fairly different than making a regular RPC:

- Streaming:

https://github.com/grpc/grpc/blob/9dfbd34f5c0b20bd77658c73c59b9a3e4e8f4e14/examples/cpp/route_guide/route_guide_client.cc#L102-L115

- Non-streaming:

https://github.com/grpc/grpc/blob/9dfbd34f5c0b20bd77658c73c59b9a3e4e8f4e14/examples/cpp/route_guide/route_guide_client.cc#L195-L200

> but if the result of `Read()` or `ExecuteSql()` is always an iteration of `Row`s, yet the caller knows there will be exactly `N` rows in the result and wants to deal with them en masse, then perhaps they just build there own `vector` from the iteration first

I am Okay with offering the same C++ API from both, but if there is a performance difference between the RPC types (I do not know that there is, that is what we should check), then we should probably let the user decide which one?

**Comment by devbww** [comment]
Ahh, yes ... I glossed over the `stream` keyword.  Thanks.  Although that then makes we question whether we ever need make use of _"resume tokens"_ (unless we're trying to mend a broken stream behind the user's back).

**Comment by coryan** [comment]
I think the resume token is in case the stream breaks (say some network flakiness) and you start a new streaming RPC but want to resume from the last thing you actually received. Pretty neat if you ask me.

**Comment by devjgm** [comment]
We have some feedback from the spanner folks that this does not matter. So always using streaming is fine.
