### ISSUE TITLE
Implement integration tests for spanner Client

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#141]
Once we have the spanner stub (#61) and client (#29) implemented, we need to add some integration tests for the Client.

**Comment by coryan** [comment]
I think we can close this. There are integration tests implemented for `Read()`, `ExecuteSql`, `Commit`, `Rollback` and `RunTransaction`.  If we think we need specific integration tests for some overload or another then we should create specific bugs for each case.

**Comment by coryan** [comment]
I broke this down into a number of issues, one for each member function that needs an integration test.
