### ISSUE TITLE
Update quickstart.cc to include our headers using angle brackets

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#1416]
After https://github.com/googleapis/google-cloud-cpp-spanner/pull/1396 is part of a release (likely, Thursday March 19), update the https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/quickstart/quickstart.cc code to include the `google/cloud/spanner/client.h` header using angle brackets rather than double quotes.

This will also require changing the quickstart's [BUILD](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/quickstart/BUILD#L23) file to link against `//:spanner_client` instead, which is the new, recommended target and the one that enables includes using angle brackets.

**Comment by coryan** [comment]
Do you want me to do this as part of the PR to update the release notes for 1.0?

**Comment by coryan** [comment]
I would guess we don't want to do this as part of the post-release changes.

**Comment by devjgm** [comment]
Right, I dropped the angle-bracket support, so I'm goign to close this issue.
