### ISSUE TITLE
[Flake] Backup integration tests still timing out in coverage builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1418]
I just had a presubmit test and a continuous integration test fail with:

```
 1/11 Test #62: backup_integration_test ..................***Timeout 2400.07 sec
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from BackupTestWithCleanup
[ RUN      ] BackupTestWithCleanup.BackupTestSuite

11/11 Test #72: samples ..................................***Timeout 2400.10 sec
Running instance admin samples on test-instance-2

Running get-instance sample
```

https://source.cloud.google.com/results/invocations/92669f4b-6a1e-4f55-8cdc-41b972d867a4
https://source.cloud.google.com/results/invocations/a2b71fa0-d802-46cf-8766-4c36ad1cb32a

**Comment by coryan** [comment]
Another one:

https://source.cloud.google.com/results/invocations/b5df577f-4c3b-4e5c-9aff-06e1bb780646/targets

**Comment by coryan** [comment]
I am tempted to disable the Backup tests in the coverage build, thoughts?

**Comment by devjgm** [comment]
SGTM, until we can come up w/ a better solution.

Also, 2 questions:

1. Are the Backup integration tests run in any other build besides coverage?

2. (If yes to above) Why are the Backup tests so slow in the coverage build and not other builds?

**Comment by coryan** [comment]
> SGTM, until we can come up w/ a better solution.
> 
> Also, 2 questions:
> 
> 1. Are the Backup integration tests run in any other build besides coverage?

No, they are only enabled if the `RUN_SLOW_INTEGRATION_TESTS` environment variable is set to `yes`, and we only do that for the code coverage build. There are a few other tests and examples that are slow, but the ones for backups are the ones timing out.


> 2. (If yes to above) Why are the Backup tests so slow in the coverage build and not other builds?

N/A

**Comment by tmatsuo** [comment]
I found out that, some of the backup operations took 30 or 40 mins.

I'd like to 1) clean up the temporary instances and 2) try only using us-west1 before disabling it.

**Comment by tmatsuo** [comment]
No, the backup operation in us-west-1 was also slow. I'd let the Spanner team look at this.
