### ISSUE TITLE
Consider running integration tests for backups with shorter timeouts

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1429]
We recently disabled the backup integration tests because they were flaking out after running for 90 (**!!**) minutes.  We discussed re-enabling the tests but with shorter timeouts.  I prototyped this idea in:

https://github.com/googleapis/google-cloud-cpp-spanner/compare/master...coryan:shorten-retry-policies-in-tests?expand=1

But I think it might not work as well as we would like. Yes, the tests will finish earlier, and it is preferable to flake in 30 minutes over 90, but they will still flake.  We could ignore errors caused by really long timeouts, but then the test loses most of its value? And cleanup becomes **very** difficult, because one cannot delete a Cloud Spanner Database with pending backups and/or restores.

**Comment by coryan** [comment]
/cc: @tmatsuo you were interested in this topic.

**Comment by tmatsuo** [comment]
For cleaning up, there are some code before some of the integration tests to delete stale instances, and the deletion will eventually succeed.

**Comment by coryan** [comment]
You cannot delete an instance with pending backups either. Does the code to delete stale instance handle that?

**Comment by tmatsuo** [comment]
The cleanup code will ignore failures on deletion, and hopefully the next run will delete it if the backup or restore operation has finished.

**Comment by tmatsuo** [comment]
We may need to recursively delete the backups in the instance.
