### ISSUE TITLE
namespace alias may be problematic

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp-spanner#1461]
In ...

1. [google/cloud/spanner/benchmarks/benchmarks_config.cc](https://github.com/googleapis/google-cloud-cpp-spanner/blob/d50058713f80d00e4954c9da75218a9b21be1340/google/cloud/spanner/benchmarks/benchmarks_config.cc#L27)
2. [google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc](https://github.com/googleapis/google-cloud-cpp-spanner/blob/d50058713f80d00e4954c9da75218a9b21be1340/google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc#L50)
3. [google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc](https://github.com/googleapis/google-cloud-cpp-spanner/blob/d50058713f80d00e4954c9da75218a9b21be1340/google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc#L31)
4. [google/cloud/spanner/samples/mock_execute_query.cc](https://github.com/googleapis/google-cloud-cpp-spanner/blob/d50058713f80d00e4954c9da75218a9b21be1340/google/cloud/spanner/samples/mock_execute_query.cc#L29)

we introduce a namespace-scoped, namespace alias for `spanner`
```
namespace spanner = ::google::cloud::spanner;
```
When any of these files includes a header that we don't fully control, or which doesn't provide sufficient cleanliness guarantees, we run the risk of clashing with an existing `namespace spanner`.

In cases 2 and 3. it is the (transitive) inclusion of generated protobuf headers that actually does cause a problem when the code is built in an environment that many of the repo owners will be familiar with.

It is probably worth our while to do something to avoid that particular clash.

**Comment by mr-salty** [comment]
FWIW, when I was working with the benchmarks a while back, I debated whether everything in there should be under `google::cloud::spanner::<anonymous_namespace>` as is the custom for tests... seems like there's a pretty good argument for that.

One issue is that `main()` can't be in the namespace and is pretty big, but it's easy enough to make a `Main()` method in the namespace and have `main()` call it.

**Comment by devjgm** [comment]
Suggestion: Put the namespace alias in the scope where it's needed (even if that's multiple aliases). I.e., Let's not declare this namespace alias in an anonymous namespace and expect it to work when use *outside* the anonymous namespace, because that *could* result in an ambiguous name.
