### ISSUE TITLE
support running integration tests against the Spanner emulator

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp-spanner#1464]
Add a wrapper to easily start and shut down an emulator for an entire test suite or for each test case.

**Comment by devjgm** [comment]
@devbww  Is this a dupe of https://github.com/googleapis/google-cloud-cpp-spanner/issues/1465?

**Comment by devbww** [comment]
In as much as this is a possible part of a solution for #1465, I'll say yes.

So, I'll close this (and note in passing that 1464 < 1465).
