### ISSUE TITLE
Sample: Developers can insert using DML

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#182]
Sample code:  https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/spanner/api/Spanner/Program.cs#L1208

This should involve creating a read-write transaction, and inserting some data into a table using DML, and committing the RW transaction using the `RunTransaction()` function.

**Comment by coryan** [comment]
The C# code linked at the top of this document is using mutations to update some rows.  So it is neither using `INSERT` nor using DML.

I think (based on the internal design doc) that we really mean the `spanner_dml_standard_insert` region tag:

https://github.com/GoogleCloudPlatform/golang-samples/blob/5ee549a58e7064dcb2345e2518f8cd377ad4a716/spanner/spanner_snippets/snippet.go#L952-L970

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/fc36ac790bc33fc0f0eae7c7b1b8cb7b81cd4c25/spanner/api/Spanner/Program.cs#L1275-L1298
