### ISSUE TITLE
Sample: Developers can update using mutations

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#184]
Sample code: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/spanner/api/Spanner/Program.cs#L1121

This should involve creating a read-write transaction, reading some data, then creating an "update" Mutation that is committed using the `RunTransaction()` funtion.

**Comment by coryan** [comment]
The golang version of this is:

https://github.com/GoogleCloudPlatform/golang-samples/blob/9dcbc6f1dc40ee9cf45ab39087602b83ffde0bb3/spanner/spanner_snippets/snippet.go#L1155

The C# version moved from the original link, now it is at:

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/fc36ac790bc33fc0f0eae7c7b1b8cb7b81cd4c25/spanner/api/Spanner/Program.cs#L1506

**Comment by coryan** [comment]
@devjgm do you remember what example what this supposed to be?  It is unclear because the link is pointing to the wrong spot.

**Comment by coryan** [comment]
By process of elimination I think this is the `spanner_udpdate_data` example, found here for golang:

https://github.com/GoogleCloudPlatform/golang-samples/blob/8d6b21976a78328274c742bcf482e3b78e3b1975/spanner/spanner_snippets/snippet.go#L519-L530

and here for C#:

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/fc36ac790bc33fc0f0eae7c7b1b8cb7b81cd4c25/spanner/api/Spanner/Program.cs#L988-L1030


I sort of implemented the C# version already, but it is obviously too ugly, I am going to implement the golang version instead.
