### ISSUE TITLE
Sample: Developers can delete using DML

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#185]
Sample code: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/spanner/api/Spanner/Program.cs#L1258

This should involve creating a read-write transaction, issuing a "DELETE" DML statement, then committing using the `RunTransaction()` funtion.

**Comment by coryan** [comment]
This seems to be the `spanner_dml_standard_delete` example, now located at:

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/fc36ac790bc33fc0f0eae7c7b1b8cb7b81cd4c25/spanner/api/Spanner/Program.cs#L1325-L1347

and

https://github.com/GoogleCloudPlatform/golang-samples/blob/9dcbc6f1dc40ee9cf45ab39087602b83ffde0bb3/spanner/spanner_snippets/snippet.go#L993-L1008

**Comment by coryan** [comment]
Fixed by #396.
