### ISSUE TITLE
Sample: Developers can delete using Mutation

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#186]
Sample code: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/spanner/api/Spanner/Program.cs#L1614

This should involve creating a read-write transaction, creating a Delete Mutation for some data, then committing using the `RunTransaction()` funtion.

**Comment by coryan** [comment]
This seems to be the spanner_delete_data sample. Located at:

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/fc36ac790bc33fc0f0eae7c7b1b8cb7b81cd4c25/spanner/api/Spanner/Program.cs#L1681-L1721


and

https://github.com/GoogleCloudPlatform/golang-samples/blob/9dcbc6f1dc40ee9cf45ab39087602b83ffde0bb3/spanner/spanner_snippets/snippet.go#L232-L249

**Comment by coryan** [comment]
Fixed by #396.
