### ISSUE TITLE
Sample: Developers can create STRUCT with data

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#187]
Sample code: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/a129e6228fb4a6cb660832168b8f02ac0675673f/spanner/api/Spanner/Program.cs#L2602
Context: https://cloud.google.com/spanner/docs/structs

**Comment by tmatsuo** [comment]
I was about to add this sample, but I have a question. For C#, it seems like there is a special purpose class [`SpannerStruct`](https://github.com/googleapis/google-cloud-dotnet/blob/18f5b83a32b7472e8cef35d8ec551482483e68eb/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerStruct.cs#L31), for go, it's just [a normal struct](https://github.com/GoogleCloudPlatform/golang-samples/blob/439a305ec9e0168e06a307f990c1e03ff28380fb/spanner/spanner_snippets/snippet.go#L284). I'm wondering how the c++ implementation will look like.

**Comment by devjgm** [comment]
We have some documentation about that in https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/value.h#L66

The short answer is that in C++ a STRUCT is represented as a `std::tuple`. The example from the value.h file is:

```cc
 using Struct = std::tuple<bool, std::pair<std::string, std::int64_t>>;
 Struct s  = {true, {"Foo", 42}};
 spanner::Value v(s);
 assert(v.is<Struct>());
 assert(s == *v.get<Struct>());
```

**Comment by tmatsuo** [comment]
Oh got it. Thanks!
