### ISSUE TITLE
Sample: Developers can query with STRUCT as bound SQL param

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#188]
Sample code: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/a129e6228fb4a6cb660832168b8f02ac0675673f/spanner/api/Spanner/Program.cs#L2610
Context: https://cloud.google.com/spanner/docs/structs

**Comment by coryan** [comment]
This is the `spanner_query_data_with_struct` sample. Note that it might have moved from the location pointed at above.
