### ISSUE TITLE
Sample: Developers can create ARRAY of STRUCT

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#189]
Sample code: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/a129e6228fb4a6cb660832168b8f02ac0675673f/spanner/api/Spanner/Program.cs#L2656
Context: https://cloud.google.com/spanner/docs/structs

In the C++ world, I think this translates to a `std::vector` of `std::tuple`

**Comment by coryan** [comment]
This is the `spanner_create_array_of_struct_with_data` sample.
