### ISSUE TITLE
Consider moving public headers to their own top-level dir

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#19]
We should consider moving the public headers into a directory like `include/google/cloud/spanner/`. This would give external users a nice and clean place to view all the public headers without being overwhelmed by the implementation details.

We'd probably need to have a bazel `BUILD` file in both the include/ tree and in the "src/" tree. Some quick experimentation suggests that we may need to add `copts = ["-Iinclude"]` to our `BUILD` rules in the src/ tree. See also https://docs.bazel.build/versions/master/cpp-use-cases.html#adding-include-paths

**Comment by devbww** [comment]
With a lack of an easy (known) solution, silence from build-help, and an existing model that no one particularly dislikes, let's maintain the status quo.  We can always change our mind before GA if something attractive comes to light.
