### ISSUE TITLE
Sample: Developers can querying using ARRAY of STRUCT

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#190]
Sample code: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/a129e6228fb4a6cb660832168b8f02ac0675673f/spanner/api/Spanner/Program.cs#L2669
Context: https://cloud.google.com/spanner/docs/structs

**Comment by coryan** [comment]
This is the `spanner_query_data_with_array_of_struct` sample.
