### ISSUE TITLE
Sample: Developers can querying using field access on nested STRUCT params

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#192]
Sample code: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/a129e6228fb4a6cb660832168b8f02ac0675673f/spanner/api/Spanner/Program.cs#L2753
Context: https://cloud.google.com/spanner/docs/structs

**Comment by coryan** [comment]
This is the `spanner_field_access_on_nested_struct_parameters` sample.
