### ISSUE TITLE
Implement spanner::Mutation Skeleton

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#198]
The spanner::Mutation class represents an [insert, update, insert_or_update, replace, or delete](https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/mutation.proto#L79-L95) operation that can be applied to a Spanner table using the spanner::Client::Commit function. This class will be a value type with the expected copy/move operations, as well as support for equality. We don't have the details of this class designed yet, but we expect to provide the obvious accessor functions, and factory functions for creating instances. The following is an outline of what this class might look like:

```cc
namespace google {
namespace cloud {
namespace spanner {

class Mutation {
 public:
  // TODO: value type, ==, !=
  // TODO: expected accessors

 private:
  // Holds a google::spanner::v1::Mutation proto
};

Mutation MakeInsertMutation(...);
Mutation MakeUpdateMutation(...);
Mutation MakeInsertOrUpdateMutation(...);
Mutation MakeReplaceMutation(...);
Mutation MakeDeleteMutation(...);

}  // namespace spanner
}  // namespace cloud
}  // namespace google
```

**Comment by coryan** [comment]
For what is worth, only delete mutations are missing, but we need key sets #202 to implement those.

**Comment by coryan** [comment]
I am going to close this in favor of #277 because that is a more specific issue.
