### ISSUE TITLE
Consider: Should we "own" GoogleCloudPlatform/cpp-docs-samples

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#200]
https://github.com/GoogleCloudPlatform/cpp-docs-samples exists. I believe it predates our supported google-cloud-cpp and google-cloud-cpp-spanner repos. The cpp-docs-samples repo appears to be fairly ignored at this point.

Should we take "ownership" of it and put our C++ samples in that repo? Should we put only "big" samples in that repo, or all of our samples? Should we deprecate that repo?

I'd be curious to understand better how other cloud client libraries use the `<lang>-docs-samples` repos.

**Comment by devjgm** [comment]
I don't think there's any urgency on this issue, but some folks who may have some input here:

@coryan @JustinBeckwith @tmatsuo @frankyn

**Comment by frankyn** [comment]
**2 cents**: Based on the CXX Cloud Summit, everyone agreed the CXX Cloud Client library team would own libraries and sample development mainly because there was no cloud DPE C++ support. 
If support hasn't changed then the repository (cpp-docs-samples) should be owned by the CXX Cloud Client library team.

**Comment by devjgm** [comment]
You can clarify if GoogleCloudPlatform/cpp-docs-samples is used for anything today? If so, what? In other words, who/what consumes the information in GoogleCloudPlatform/cpp-docs-samples?

**Comment by frankyn** [comment]
Ah, looping in @surferjeffatgoogle

**Comment by JustinBeckwith** [comment]
I have no idea what that repo is used for today, or if it's linked at all within cloud site.  Given that this is all new fresh shiny code, I would very much prefer that *samples live with the sources*.  With node.js, we have a `samples/` directory right in the same repo as the sources, so we can do things like run sample tests directly against master.  This is super useful to make sure we don't break anything customers are using.

I would very much prefer we do the same :)  For @tmatsuo, I would:
- Do an audit of cloud site.  Are we referencing any of the samples used in that GitHub repo?
- If not, let's archive it
- If we are, can we move them to the relevant split repos?

**Comment by JustinBeckwith** [comment]
@devjgm I think for spanner, we decided that samples go in this repo - right?  If so, can we close this out?  @tmatsuo is tackling the more general problem of "what do we do with cpp-docs-samples".

**Comment by tmatsuo** [comment]
right
