### ISSUE TITLE
Implement spanner::Key, spanner::KeySet

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp-spanner#202]
Implement the Key and KeySet classes.

```cc
namespace google {
namespace cloud {
namespace spanner {
class Key { 
 public:  
  template <typename... Ts>  // TODO: Add appropriate enabler
  explicit Key(Ts&&... ts);
  // Value type, op==, op!=
  // ...
};

class KeySet {
 public:
  static KeySet All() { return KeySet(all_tag{}); }
  KeySet() = default;
   // TODO: Make this a value type with op==, op!=
  // TODO: Add support for key ranges

  void Add(Key key);
};
}  // namespace spanner
}  // namespace cloud
}  // namespace google
```
Please include all reasonable boilerplate code, copyright notices, basic doxygen comments, and `.h`, `.cc`, and `_test.cc` files.

## Design notes
A spanner::KeySet is an argument to the spanner::Client::Read functions. Keys may be specified as individual keys, key ranges (with open or closed intervals), or a special "all keys" token. A "key" consists of the value(s) for the column(s) used in the named index. This is encapsulated by the spanner::Key class. 

A spanner::Key is very similar to a `std::vector<spanner::Value>`, except that a Value can be "null" while a Key cannot. We may be able to invent a more general concept that covers both needs.

**Comment by devjgm** [comment]
Just something for us to consider...

Now that we have `Row<Ts...>` (https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/row.h) we may want to consider whether a `Row` is a good replacement for `Key`. I do think we probably want a `KeySet` still, but I could imagine a `KeySet` object on which we call `.AddRow(...)`. 

We'd have to think about how that plays with templates, how we convert the Row -> proto values, etc. But something to consider.

**Comment by devjgm** [comment]
... more thinking....

We already have `ParseRow` (https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/row.h#L289) that converts from an `std::array<Value, N>` to a `Row<Ts...>`. We'd need the opposite function to convert from a `Row<Ts...>` to a `std::array<Value, sizeof...(Ts)>`. Let me call that function `UnparseRow()` for a moment.

If we had `UnparseRow()`, we may be able to use the type `Row<Ts...>` as the "Key" type in the KeySet, and we'd be able to convert each "row key" into the appropriate Values and protos needed to create the gRPC requests.

I have a little sketch of this `UnparseRow` function on a branch, and it's pretty straight forward. So I think we can *consider* this as a viable alternative to inventing a new `Key` type. (though, perhaps there's still value in having a Key abstraction).

**Comment by devjgm** [comment]
I think this may be done now? @scotthart

**Comment by scotthart** [comment]
It is done.
