### ISSUE TITLE
ci/kokoro/install/build.sh's caching behavior is broken

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp-spanner#213]
How to reproduce:

Add the following to `ci/kokoro/install/Dockerfile.fedora`:

```Dockerfile
WORKDIR /var/tmp/ci
COPY install-bazel.sh /var/tmp/ci
RUN /var/tmp/ci/install-bazel.sh
```

Run the following commands:

```shell
sudo docker build --target devtools -t test-install-fedora:latest \
    -f ci/kokoro/install/Dockerfile.fedora ci/
sudo docker build --cache-from=test-install-fedora:latest --target install \
    -f ci/kokoro/install/Dockerfile.fedora .
```

It will fail at this step:

```
Step 24/43 : WORKDIR /var/tmp/ci
 ---> Using cache
 ---> bb5f10058c65
Step 25/43 : COPY install-bazel.sh /var/tmp/ci
COPY failed: stat /home/tom/second_drive/docker/tmp/docker-builder611793550/install-bazel.sh: no such file or directory
```

**Comment by remyabel** [comment]
Either I made a typo or don't understand how `cache-from` works, but it appears that changing the build context will screw with the cache and cause the first stage to be rebuilt. `ci/kokoro/install/build.sh` is essentially copied from `google-cloud-cpp` so there must be something done differently here.

**Comment by coryan** [comment]
Should the second command be:

sudo docker build --cache-from=test-install-fedora:latest --target install \\
  -f ci/kokoro/install/Dockerfile.fedora **ci**

? I think changing the path invalidates the cache and (incidentally), makes `install-bazel.sh` not exist...

**Comment by remyabel** [comment]
We're using `.` here as well: https://github.com/googleapis/google-cloud-cpp/blob/master/ci/kokoro/install/build.sh#L107

My impression was that for the devtools stage we set the build context *only* to `ci`  but use the whole directory for the install stage (since we are doing `COPY .`, but I could be mistaken). 

Furthermore, I have not tested it, but I wonder if mixing in `docker pull/push` gets around this problem.

**Comment by coryan** [comment]
Ah... do you want `RUN /var/tmp/ci/install-bazel.sh` in the `install` or `devtools` stage?

**Comment by remyabel** [comment]
Logically, the correct place to run it would be the `devtools` stage, since we do not want to re-install Bazel all the time. But given that changing the build context results in funky behavior, for now, it will have to be in the `install` stage. Alternatively, we could just use a separate build for Bazel alone.

**Comment by coryan** [comment]
> Logically, the correct place to run it would be the `devtools` stage, since we do not want to re-install Bazel all the time.

Ack.

> But given that changing the build context results in funky behavior,

What happens if we change this:

https://github.com/googleapis/google-cloud-cpp/blob/master/ci/kokoro/install/build.sh#L91

to use `.`?

> for now, it will have to be in the `install` stage. Alternatively, we could just use a separate build for Bazel alone.

I assume you are trying to enable caching for the `install` builds?  How does Bazel come into the picture with `install`?

**Comment by remyabel** [comment]
> I assume you are trying to enable caching for the install builds? How does Bazel come into the picture with install?

Nope, I'm trying to do the bazel-dependency test install. I do not have the proper permissions to implement the caching TODO.

> What happens if we change this:

Yep, I'll try that, but since we are doing `docker build "${devtools_flags[@]}" ci` to make the builds faster I will proceed with making it a separate build for now.

**Comment by coryan** [comment]
> Nope, I'm trying to do the bazel-dependency test install.

Ack.

> but since we are doing `docker build "${devtools_flags[@]}" ci` to make the builds faster I will proceed with making it a separate build for now.

Thanks. Separate build does sound better for this case.

**Comment by remyabel** [comment]
Are the Kokoro builds using some environment variables/settings that makes Bazel install in `$HOME/bin` instead of `/usr/local/bin`?

**Comment by remyabel** [comment]
Nevermind, I see that it's doing a user install since the username is `kbuilder`. Also closing this since discussion is resolved.
