### ISSUE TITLE
Determine the return type to use for `ResultSet::stats()`

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#217]
The skeleton for `ResultSet::stats()` returns the [proto `ResultSetStats` type](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.ResultSetStats).  Determine if this is sufficient, or if we should provide other types to return here.

**Comment by mr-salty** [comment]
Some notes:

* There are three main things (currently) returned: the query plan, the statistics, and a row count (which can be approximate or exact based on the query).
* [`QueryPlan`](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.QueryPlan) in particular may benefit from a friendlier type.
* it's unclear if the structure of `query_stats` is fixed enough to use a C++ struct, or if has to be a key/type/value like Struct.
* row counts are pretty simple.

**Comment by devjgm** [comment]
Is there anything in the stats that we think we really need in Alpha? Or is this mostly a post-alpha (likely "beta") issue?

**Comment by mr-salty** [comment]
could probably be beta?

**Comment by mr-salty** [comment]
Note this also applies to the return value of Client::ExecuteBatchDml()

**Comment by scotthart** [comment]
query_stats is a collection key-value pair (both strings) statistics that have been aggregated from the key-value pair statistics present in the individual nodes in the query_plan.
