### ISSUE TITLE
Audit use (or lack of use) of `noexcept`

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#228]
We are probably not using `noexcept` in all the places we should. I *think* the result of this is potentially leaving some performance on the floor; I don't think there would be actual bugs because of this. However, at some point, we someone should give us a good rule-of-thumb for when and what to mark `noexcept`, then maybe do a little audit of some parts of this code to make sure we're using it appropriately where it's needed.

I think this is fairly low priority.

**Comment by devbww** [comment]
Rule of thumb #&#x2060;1: Use `noexcept` on every explicit move constructor and `swap()` implementation.

**Comment by devbww** [comment]
For the record, as of 2020-01-16 we have two uses of `noexcept`:
1. On the move ctor/assign for `g::c::spanner::Mutation`, and
1. On the ctor for `g::c::spanner::internal::Session`.

**Comment by devbww** [comment]
A corollary of the rule of thumb is that `noexcept` should not be specified on defaulted move ctor/assign.  Those defaulted functions will derive their `noexcept`-ness from the member-wise pieces.

Given that we haven't hand written any move ctor/assign or `swap()`s to date, we shouldn't have any `noexcept`s either.
