### ISSUE TITLE
For super build, installed libraries can conflict with those in $HOME/local

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp-spanner#249]
I get non-fatal warnings like the following:

```
CMake Warning at google/cloud/storage/examples/CMakeLists.txt:56 (add_executable):
  Cannot generate a safe runtime search path for target
  storage_notification_samples because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libcares.so.2] in /usr/lib64 may be hidden by files in:
      /home/tom/local/lib
    runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      /home/tom/local/lib

  Some of these libraries may not be found correctly.
```

These warnings do *not* appear in the build output for the Kokoro build. I suspect this is because the conflicting libraries aren't installed by the package manager in the Dockerfile.

I am unsure how dangerous this warning is, but might be worth fixing.

**Comment by remyabel** [comment]
As an addendum, I'm currently trying to add the super build to google-cloud-cpp in the readme Dockerfile. When using `-DCMAKE_BUILD_TYPE=Debug`, I observe the following:

On my system, I see that it finds my system GTest and not the one in `$HOME/local`:

```
-- Found ZLIB: /home/tom/local/lib/libz.so (found version "1.2.11") 
-- Found ProtobufTargets: TRUE  
-- Found Protobuf: /home/tom/local/lib/libprotobuf.a;-lpthread (found version "3.7.1") 
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1c")  
-- Performing Test GOOGLE_CLOUD_CPP_COMPILER_SUPPORTS_WALL
-- Performing Test GOOGLE_CLOUD_CPP_COMPILER_SUPPORTS_WALL - Success
-- Performing Test GOOGLE_CLOUD_CPP_COMPILER_SUPPORTS_WEXTRA
-- Performing Test GOOGLE_CLOUD_CPP_COMPILER_SUPPORTS_WEXTRA - Success
-- Performing Test GOOGLE_CLOUD_CPP_COMPILER_SUPPORTS_WERROR
-- Performing Test GOOGLE_CLOUD_CPP_COMPILER_SUPPORTS_WERROR - Success
-- Performing Test CXX_SUPPORTS_COVERAGE_FLAG
-- Performing Test CXX_SUPPORTS_COVERAGE_FLAG - Success
-- clang-tidy found: /usr/bin/clang-tidy
-- Found GTest: /usr/lib64/libgtest.so 
```

When GTest is *not* installed by the package manager (i.e, in the Dockerfile), then it can't find it at all:

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindGTest.cmake:197 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/IncludeGMock.cmake:56 (find_package)
  cmake/GoogleCloudCppCommon.cmake:46 (include)
  google/cloud/CMakeLists.txt:62 (include)
```

even though the artifacts exist in `$HOME/local`. I suspect the way we're looking for the debug files in `IncludeGMock` is problematic for the super build.

**Comment by remyabel** [comment]
I deleted the previous comment because I can no longer reproduce it. Maybe it's a heisenbug?

**Comment by remyabel** [comment]
Looking again at the warnings, it appears to only be complaining about `google/cloud/storage` and `libcares` and `libz`. Looking at the link one for one of the targets:

```
/usr/bin/ccache /usr/lib64/ccache/c++     
CMakeFiles/storage_default_object_acl_samples.dir/storage_default_object_acl_samples.cc.o  
-o storage_default_object_acl_samples -Wl,-rpath,/home/tom/local/lib 
../libstorage_client.a ../../libgoogle_cloud_cpp_common.a 
/home/tom/local/lib64/libcrc32c.a /home/tom/local/lib/libcurl.so 
-ldl /usr/lib64/libcares.so /usr/lib64/libssl.so /usr/lib64/libcrypto.so 
/usr/lib64/libz.so -lpthread /usr/lib64/libssl.so /usr/lib64/libcrypto.so 
/home/tom/local/lib/libz.so
```

Notice how it's linking against both `/usr/lib64/libz.so` and `/home/tom/local/lib/libz.so`.

**Comment by remyabel** [comment]
The culprit seems to be the curl external project. Observe:

```
cmake-out/external/curl/src/curl-project-build/CMakeCache.txt:CARES_LIBRARY:FILEPATH=/usr/lib64/libcares.so
cmake-out/external/curl/src/curl-project-build/CMakeCache.txt:ZLIB_LIBRARY_RELEASE:FILEPATH=/usr/lib64/libz.so
```

Comparatively, Protobuf for example finds the correct ZLIB:

```
cmake-out/external/protobuf/src/protobuf-project-build/CMakeCache.txt:ZLIB_LIBRARY_RELEASE:FILEPATH=/home/tom/local/lib/libz.so
```

This problem does *not* exist for the readme builds in `google-cloud-cpp` (`sudo docker build -f ci/kokoro/readme/Dockerfile.fedora .`), which tests the external projects.

**Comment by coryan** [comment]
Ack.  Maybe we should consider removing libcurl and zlib from the list of external projects, and (like openssl and the C++ library) just assume that they are provided by the OS.  This is reasonable on Linux, mostly Okay on macOS, I am not sure how well it works on Windows.

On the other hand, we assume that OpenSSL is installed on Windows, typically via vcpkg, so maybe we can assume the same for libcurl and zlib?
