### ISSUE TITLE
Create CI build on Windows + CMake.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#267]

**Comment by coryan** [comment]
For what is worth, I have a draft version of this at:

https://github.com/coryan/google-cloud-cpp-spanner/tree/manual-windows-build-support

@tmatsuo because that might be useful for the work on Windows+Bazel too.

**Comment by tmatsuo** [comment]
Trying to do similar thing without docker for now, now I'm getting:

```
..\..\..\..\..\..\google\cloud\spanner\internal\retry_loop_test.cc(16): fatal error C1083: Cannot open include file: 'google/cloud/testing_util/assert_ok.h': No such file or directory
```
There is the file in the local install directory though.

**Comment by coryan** [comment]
What is the name of the install directory? And can you share the build command that failed?

**Comment by tmatsuo** [comment]
Seems like it's working by setting CMAKE_CXX_FLAGS

**Comment by coryan** [comment]
Glad to hear it it working.  We should not need to set CMAKE_CXX_FLAGS.  If we have to, that means one or more of the targets are not exporting the requirements correctly, i.e., there is a defect in `make install` or something like that.

**Comment by tmatsuo** [comment]
Now it compiles and unit tests are green. I'll send a PR.

I still can not run the integration tests with the following:

```
6/6 Test #45: samples ..................................Exit code 0xc0000409
***Exception:  23.51 sec
E0909 21:19:43.665000000  2552 oauth2_credentials.cc:220] oauth_fetch: {"created":"@1568063983.665000000","description":"Failed HTTP requests to all targets","file":"T:\src\github\vcpkg\buildtrees\grpc\src\v1.23.0-e6e5efec9c\src\core\lib\http\httpcli.cc","file_line":202,"referenced_errors":[{"created":"@1568063983.665000000","description":"Failed HTTP/1 client request","file":"T:\src\github\vcpkg\buildtrees\grpc\src\v1.23.0-e6e5efec9c\src\core\lib\http\httpcli.cc","file_line":113,"referenced_errors":[{"created":"@1568063983.665000000","description":"OS Error","file":"T:\src\github\vcpkg\buildtrees\grpc\src\v1.23.0-e6e5efec9c\src\core\lib\iomgr\tcp_client_windows.cc","file_line":106,"os_error":"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\r\n","syscall":"ConnectEx","target_address":"ipv4:169.254.169.254:80","wsa_error":10060}]}]}
E0909 21:19:45.139000000  2552 client_context.cc:91] assertion failed: call_ == nullptr
```

**Comment by tmatsuo** [comment]
Windows CMake builds are live now. They don't run the integration tests though.

We'll enable the integration tests later:
https://github.com/googleapis/google-cloud-cpp-spanner/issues/601

Closing
