### ISSUE TITLE
Fix include guards

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#273]
Our include guards are supposed to start with the project name, which is `GOOGLE_CLOUD_CPP_SPANNER_`, but https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/ci/check-include-guards.gawk#L29 is requiring that our guards start with `GOOGLE_CLOUD_CPP_`.

We should fix that script, and fix all the project include guards.

**Comment by devbww** [comment]
So, for example, we're looking for `GOOGLE_CLOUD_CPP_SPANNER_GOOGLE_CLOUD_SPANNER_VERSION_INFO_H_`, yes?

**Comment by devjgm** [comment]
Yep. https://google.github.io/styleguide/cppguide.html#The__define_Guard

"All header files should have #define guards to prevent multiple inclusion. The format of the symbol name should be <PROJECT>_<PATH>_<FILE>_H_"

It's verbose, but I think it's what's recommended by the style guide.
