### ISSUE TITLE
Design and implement sequence number management

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#279]
DML operations (via `ExecuteSql` or `ExecuteBatchDmlRequest`) require a per-transaction sequence number. Ideally we can manage this for the user.

https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner.proto#L441

> A per-transaction sequence number used to identify each request. This makes each request idempotent such that if the request is received multiple times, at most one will succeed.
>   
> The sequence number must be monotonically increasing within the transaction. If a request arrives for the first time with an out-of-order sequence number, the transaction may be aborted. Replays of previously handled requests will yield the same response as the first execution.
>   
> Required for DML statements. Ignored for queries.

**Comment by mr-salty** [comment]
FYI, looks like Java manages this automatically: [code link](https://github.com/googleapis/google-cloud-java/blob/2ae5ca09b1a5537410300d9187bfefe998d9f086/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java#L367)

Write data with DML" example here also doesn't show the user managing sequence numbers: https://cloud.google.com/spanner/docs/getting-started/java/

One thing we have to decide is what happens if the user calls `ExecuteSql` from multiple threads with the same `Transaction`. It seems the "most correct" thing is to take a (per-transaction?) lock, increment the sequence number, make the RPC, and then drop the lock. But, holding a lock while making a remote call is questionable. So, perhaps we should just document that this should not be done and the results are undefined.

**Comment by coryan** [comment]
> 
> One thing we have to decide is what happens if the user calls `ExecuteSql` from multiple threads with the same `Transaction`.

I guess the first question is whether we plan to support that use-case. I think we should certainly support a `Transaction` used in multiple threads, but maybe not at the same time?  If we do decide to support multiple threads using the same `Transaction` simultaneously there are additional considerations:

> It seems the "most correct" thing is to take a (per-transaction?) lock, increment the sequence number, make the RPC, and then drop the lock.

As you point out below, holding the lock while making an RPC is questionable. And that will not work with asynchronous RPCs if/when we decide to introduce those.  We may want the transaction to wrap or represent (borrowing a concept from Boost.Asio/executors) a [strand](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/overview/core/strands.html).

> But, holding a lock while making a remote call is questionable. So, perhaps we should just document that this should not be done and the results are undefined.

One of the use-cases we mentioned in internal discussions was a middle-tier server, e.g., a web-server that uses Spanner as a backend to serve user content. Such a server may receive a request, create a transaction to handle this request, and then make multiple queries using that transaction, maybe from different threads.

This is all to say: this topic seems more complex to me than what can be reasonably written down in an issue. We need a design doc.

**Comment by coryan** [comment]
A couple of other issues to think about

* gRPC channels may have multiple sub channels under the hood, I do not think there is a guarantee that requests arrive in the same order they were sent.

* We may need to re-home a session (and therefore its current transaction, if any) when the gRPC channel is dropped and we reconnect.

**Comment by devbww** [comment]
There is still the question of how any sequencing requirements for operations within a transaction are either communicated to the user or modeled in the API.

**Comment by devjgm** [comment]
https://github.com/googleapis/google-cloud-cpp-spanner/pull/331 added support for sequnece numbers.

Can someone clarify what remains to be done for this issue?

**Comment by devbww** [comment]
It looks to me like the sequence numbers were then plumbed into the appropriate protos in #350, so my take is that nothing remains to be done.
