### ISSUE TITLE
make the clang-tidy build run clang-tidy

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#28]
The existing clang-tidy build runs clang-format but does not run clang-tidy
Note this applies to the other repo as well.

https://github.com/googleapis/google-cloud-cpp-spanner/blob/f2c7b4084f3aec736fd89e49ab175f16c4ed399d/ci/check-style.sh

**Comment by coryan** [comment]
Is this a dup of #25?  And why do you think "the other repo" is not running clang-tidy?

**Comment by mr-salty** [comment]
Yes - dup of #25 - sorry, I didn't see that.

As far as the other repo, that was a misunderstanding on my part, when I saw clang-tidy wasn't being run here I tried to figure out how it was run there; I searched for  'clang-tidy' and when I didn't see it being invoked I assumed it wasn't running there either... but I see now that it happens via CMake - sorry.
