### ISSUE TITLE
Implement Transaction::PartitionedDmlOptions

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#287]
We also need to add an overload to `Client::ExecuteSql` to accept an argument of type `Transaction::PartitionedDmlOptions` (just like how SingleUseOptions works today).

NOTE: there are no actual options today, but there might be some someday.

**Comment by devbww** [comment]
In the name of "actively working on", I'm going to unassign this.  I'll keep the code around should thinking return to the current wording of the issue.

For the record, this is a prerequisite for #432.

**Comment by coryan** [comment]
Well, I think we are going to need to call `BeginTransaction()` API explicitly, whether we want it or not.  I just wrote a test and I got this:

```
[ RUN      ] ClientIntegrationTest.ExecuteSqlPartitionDml
google/cloud/spanner/integration_tests/client_integration_test.cc:363: Failure
Value of: result
Expected: is OK
Actual: PartitionedDml Transactions must be created with the BeginTransaction API [INVALID_ARGUMENT]
```

**Comment by devbww** [comment]
Thanks for clarifying that.

> we could make a BeginTransaction() call first in our ExecuteSql() implementation if s.begin().has_partitioned_dml(), so it wouldn't change any user API.

I'll add a marker for that in my pending PR, which I can then fill in if we decide `ExecuteSql()` is the right user interface.

**Comment by devjgm** [comment]
FTR, after talking about this I believe we decided on the following:

* Use a differently named function, like `Client::ExecutePartitionedDml(SqlStatement)`
* Also provide a virtual overload for this differently named function in `connection.h`
* The return type should probably be something that's more natural for this type of DML. Perhaps something like `StatusOr<PartitionedDmlResult>`, which is a struct (in a separate file) that has the info that's meaningful for this type of query. (it may be a single int w/ a row count or something)

Opinion: Also, I'll add that due to the odd nature of PartitionedDml transactions (i.e., they must be created with `BeginTransaction`, and they cannot be committed), I do not think we need to or should expose anything about Partitioned DML transactions in any of the transaction files or classes. I think we can make all the Partitioned DML transaction stuff be a complete implementation detail inside `connection_impl.cc`.
