### ISSUE TITLE
Create class/function to calculate Database Name

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#301]
A Spanner database name includes a project-id, instance-id, and database-id. In RPCs it's represented as a string of the form `projects/<project-id>/instances/<instance-id>/databases/<database-id>`. This will be hard for users to type correctly, so we should provide a helper function or class to compute these for users. But we need to pick whether to go with a function or class.

### Option: Function

```cc
// Returns a string of the form:
// "projects/<project-id>/instances/<instance-id>/databases/<database-id>"
std::string DatabaseName(
    std::string const& project_id,
    std::string const& instance_id,
    std::string const& database_id);
```
Other functions that need a database name would accept the parameter as a `std::string` and document that callers can use this `DatabaseName(...)` helper function to compute the string.

Pros:
* Easy to implement

Cons:
* Not type safe; the requirements of a `std::string database_name` argument are not captured in the type system.

### Option: class
```cc
class DatabaseName {
 public:
  DatabaseName(std::string project_id, std::string instance_id, std::string database_id);
  // Regular type: copy, assign, move, all `=default`

  // Accessors
  std::string const& project_id() const;
  // Also for instance_id and database_id

  // Returns the fully qualified database name of the form:
  // "projects/<project-id>/instances/<instance-id>/databases/<database-id>"
  std::string QualifiedName() const;

  // Maybe, because convenient, and there's a clear stringable format?
  std::ostream& operator<<(std::ostream& out, DatabaseName const& dn);

  friend bool operator==(DatabaseName const& a, DatabaseName const& b);
  friend bool operator!=(DatabaseName const& a, DatabaseName const& b);

 private:
  // 3 fields for project_id, instance_id, database_id
};
```

Pros:
* Clear meaning and type safe at all call sites.

Cons:
* A little more to implement, but still a pretty trivial C++ "value type"
* Maybe overkill?
* Less convenient if users already have the fully qualified string that they want to use (though, we could provide a method that parses that and turns it into a `DatabaseName` if such a need arises).

---

I think I lean toward the class approach because I think the type safety and the self-documenting code are valuable.

Related: #295

**Comment by devbww** [comment]
See `google/cloud/spanner/client.h:MakeDatabaseName()`.

**Comment by devjgm** [comment]
Oops. I didn't know that function was added already. My mistake. The function LGTM. Thanks.
