### ISSUE TITLE
Consider: Factoring the spanner connection out of the Client

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#305]
There are two potential issues that when considered together may suggest a slight alternative design to how we construct `Client` objects. The issues are:

### grpc::Channel reuse

I believe our plan today is to construct `Client` objects roughly as follows:

```cc
ClientOptions opts;   // [1]
Client c = MakeClient("/database/name", opts);  // [2]
```
The `ClientOptions` created in [1] above include the `grpc::ChannelCredentials` and the endpoint name (e.g., "spanner.googleapis.com"). Both of these fields have good defaults and are optional.

The call to `MakeClient` in [2] above results in the creation of a new `grpc::Channel`, which is expensive and should be reused as much as possible. We could maintain a channel-pool of our own to minimize the number of new channels we create, but there might be a better idea given the next point.

### Users need to be able to test with "mocks"

For the Alpha launch we need to enable developers to write their own unit tests with mocks of our client (See #196). The obvious solution for this is to make our `Client` class an interface with pure-virtual methods that are amenable to mocking. The problem with this is that virtual interfaces have some downsides in that they don't play well with overloading, nor templates, nor traditional "value semantics".

Another solution is to provide a non-virtual regular type named `Client` that users interact with (exactly as we do today), but then allow users to optionally *inject* in an object that implements some virtual interface that can be mocked. Indeed, this is pretty much exactly the plan we are doing today: https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/client.h#L361

FTR, I like this idea

The issues with today's plan are:

1. The injected interface is `internal::SpannerStub`, which as its name implies is "internal" and should not be used, implemented, or mocked by end users.

2. The API of [`SpannerStub`](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master//google/cloud/spanner/internal/spanner_stub.h) is written in the vocabulary of the gRPC API, not the vocabulary of `Client`. This means that if users are two write their own tests, they need to learn the gRPC API in order to correctly mock `Client`. For example, `SpannerStub` talks about sessions, and "BeginTransaction", and gRPC protobufs, all of which we've tried to hide.

### Proposed Solution

Expose the concept of a "Connection", which is a logical connection to Spanner. It would encapsulate both a grpc::Channel and a the service-specific "stub". The Connection would be created with the users credentials and the endpoint name, both of which are optional, because there are good defaults. 

`spanner::Connection` would be an interface class that would be written completely in the vocabulary of `spanner::Client`. Users *could* mock the `spanner::Connection` class and inject it into their `Client` objects in order to write their own unit tests. It's interface would look something like:

```cc
class Connection {
 public:
  struct ReadParams {
    std::string table;
    KeySet keys;
    // ...
  };
  virtual StatusOr<ResultSet> Read(ReadParams const&) = 0;

  struct ExecuteSqlParams {
    SqlStatement statement;
    // ...
  };
  virtual StatusOr<ResultSet> ExecuteSql(ExecuteSqlParams const&) = 0;

  // ...
};
```

That is, there would be *one* pure-virtual method in this interfae for each logical operation provided by Client. For example, all of Client's `Read()` overloads would call through to the one `Read(ReadParams const&)` pure-virtual method in the Connection interface. This would give callers a single method to mock that would work with all of our convenient overloads.

The `Client` class would then be constructed with a "Connection". Users could create many `Client` objects all using the same "Connection" and this would be efficient and encouraged.

Example code:

```cc
// Optionally pass credential and endpoint to MakeConnection()
std::shared_ptr<spanner::Connection> conn = spanner::MakeConnection();
Client c1("/database/name", conn);
Client c2("/other/db", conn);  // OK, also uses conn
```

### FAQ

**What about the admin interface?**

That would be a different type of Connection class. Call it `spanner::AdminConnection`. But the exact same ideas would apply. It would work well and fit in nicely, I think.

**Are other Spanner libraries designed like this?**

Yes. For example, [C#](https://cloud.google.com/spanner/docs/reference/libraries#client-libraries-usage-csharp), [Java](https://cloud.google.com/spanner/docs/reference/libraries#client-libraries-usage-java), and maybe others.

**Why don't we just expose `SpannerStub` to users?**

Because it's an API written with the wrong vocabulary. It's a thin wrapper above gRPC, but that's an API that we're hiding from users. For example, our users don't care about "begin transaction", or "sessions", but we need `SpannerStub` to expose those methods for our *implementation*.

**Will we still need the `SpannerStub`?***

Probably, yes. That stub is a wrapper over the grpc-generated API, and providing that wrapper will help us unit test *our own* code. But it's an internal thing and will not help our users test their code.

### Steps

We've talked about this a fair bit in person in the office, but I'd like to hear others' opinions. (e.g., @coryan ). If we decide to do this, I think the steps would be something like this

- [ ] Define the `Connection` interface class. This should not be very difficult. It will basically be a single pure-virtual method for each overload set we expose in `Client`. To future-proof this interface, I think the methods on `Connection` should all take "params" structs instead of separate arguments, that way we can add more over time without breaking existing mocks. **effort: low**

- [ ] Implement a `internal::ConnectionImpl` subclass of `spanner::Connection` that implements each of the methods using the existing `internal::SpannerStub`. Initially, most of these methods will be noops, or TODOs, just like they are in `Client` today. **effort: medium**

- [ ] Expose a `spanner::MakeConnection()` method. It should return a `std::shared_ptr<spanner::Connection>` pointing to an `internal::ConnectionImpl` instance. It should optionally accept `grpc::Credential` and an endpoint string. **effort: low**

- [ ] Change `Client` to accept a `std::shared_ptr<spanner::Connection>` argument. Each of Client's methods should populate the params struct and call the pure-virtual method on the Connection object. **effort: med**

- [ ] Do the equivalent changes for the admin interface.

**Comment by coryan** [comment]
I will take it as a given that exposing the implementation vocabulary for mocking is a "Bad Thing":tm:. 
 Personally it would not bother me if I have to use implementation vocabulary to mock, I am sort of messing with the implementation anyway :shrug:  So LGTM, in general, with a couple of nits:

> We could maintain a channel-pool of our own to minimize the number of new channels we create,

If this was intended as a global pool across clients, I do not think we need it: gRPC pools connections / channels anyway, so why pool again?  We probably want create a pool of channels in each *Client* (see below).

> It would encapsulate both a grpc::Channel

It is very likely that we will want to pool multiple `grpc::Channel` objects in a single client / connection / stub. There is a practical limit to the number of outstanding requests that we can have per channel, and we probably want to round-robin across many channels to get good throughput through a single Client.

In some rare cases the application may want a separate pool for `client1` vs. `client2` (to avoid priority inversions).  We support this in Bigtable by naming the channel pools via the `ClientOptions`. It is a obscure feature, and rarely needed, but it is there. 

> and a the service-specific "stub". 

The `*Stub` classes already encapsulate a channel... did you mean for the connection to really have a separate `grpc::Channel` and `*Stub` member variables and somehow pass the channel to the stub?

> *  Implement a `internal::ConnectionImpl` subclass of `spanner::Connection` that implements each of the methods using the existing `internal::SpannerStub`. Initially, most of these methods will be noops,

nit: Consider simply *not* adding the member functions until they are needed.

**Comment by devjgm** [comment]
I think it would be a better user experience if users could create a mock `spanner::Client` and only have to override methods that look pretty much like the existing `Client` methods that they already understand. Otherwise, almost all users (or all users who want to write unit tests), would need to lear the `Client` API *and* the gRPC API. So I don't think that would be a great user experience. But if the team thinks that's not bad, then we could simply make the existing `internal::SpannerStub` class non-internal and document it for users.

> If this was intended as a global pool across clients, I do not think we need it: gRPC pools connections / channels anyway, so why pool again? 

I didn't know gRPC already pools channels. I thought they were expensive to create and should be re-used. Is that not the case?

> It is very likely that we will want to pool multiple grpc::Channel objects in a single client / connection / stub. There is a practical limit to the number of outstanding requests that we can have per channel, and we probably want to round-robin across many channels to get good throughput through a single Client.

I think this could be done easily in the proposed `spanner::Connection` object. That is, it could maintain the pool of grpc::Channels if needed.

> In some rare cases the application may want a separate pool for client1 vs. client2 (to avoid priority inversions). We support this in Bigtable by naming the channel pools via the ClientOptions. It is a obscure feature, and rarely needed, but it is there.

This would be easy/natural in this proposed design. The user would just create separate `spanner::Connection` objects, and give one to `client1` and another to `client2`.

> The *Stub classes already encapsulate a channel... did you mean for the connection to really have a separate grpc::Channel and *Stub member variables and somehow pass the channel to the stub?

I just meant that a `spanner::Connection` would have a grpc "stub" and the channel. As far as passing the channel to the stub, that would just be [the same as it is today](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/internal/spanner_stub.cc#L243). But maybe I'm not understanding the question.

> nit: Consider simply not adding the member functions until they are needed.

Ack. I like this. Good suggestion.

**Comment by coryan** [comment]
> I think it would be a better user experience if users could create a mock `spanner::Client` and only have to override methods that look pretty much like the existing `Client` methods that they already understand.

Agreed.

> Otherwise, almost all users (or all users who want to write unit tests), would need to lear the `Client` API _and_ the gRPC API. So I don't think that would be a great user experience.

Having to mock the gRPC APIs is a worse experience.  It would not bother *me*, but I think my intuition may be off: I work with gRPC too much.

> But if the team thinks that's not bad, then we could simply make the existing `internal::SpannerStub` class non-internal and document it for users.

Ack. Don't over-weight my opinion here.  While it would not bother *me* to use gRPC APIs, it might be annoying to other users.

> 
> > If this was intended as a global pool across clients, I do not think we need it: gRPC pools connections / channels anyway, so why pool again?
> 
> I didn't know gRPC already pools channels. I thought they were expensive to create and should be re-used. Is that not the case?

The documentation is not super clear, I found this blog post that states they are pooled:

https://grpc.io/blog/grpc_on_http2/

and I remember discussing this with the gRPC folks.  My observation was that channels got pooled by gRPC, but how that pool works I do not know in detail.


> 
> > It is very likely that we will want to pool multiple grpc::Channel objects in a single client / connection / stub. There is a practical limit to the number of outstanding requests that we can have per channel, and we probably want to round-robin across many channels to get good throughput through a single Client.
> 
> I think this could be done easily in the proposed `spanner::Connection` object. That is, it could maintain the pool of grpc::Channels if needed.

Ack, I was thinking that this would live lower in the stack (the bottom `*Stub`) but maybe it can be higher up. We need to tie the channel to the sessions, so higher might be better.

> 
> > In some rare cases the application may want a separate pool for client1 vs. client2 (to avoid priority inversions). We support this in Bigtable by naming the channel pools via the ClientOptions. It is a obscure feature, and rarely needed, but it is there.
> 
> This would be easy/natural in this proposed design. The user would just create separate `spanner::Connection` objects, and give one to `client1` and another to `client2`.

So here is where the gRPC pooling gets in the way. It magically pools all your connections, even if you call "MakeBlahBlahChannel" again.  You need to set a custom key to separate the pools:

https://github.com/googleapis/google-cloud-cpp/blame/master/google/cloud/bigtable/internal/common_client.cc#L28

> 
> > The *Stub classes already encapsulate a channel... did you mean for the connection to really have a separate grpc::Channel and *Stub member variables and somehow pass the channel to the stub?
> 
> I just meant that a `spanner::Connection` would have a grpc "stub" and the channel. As far as passing the channel to the stub, that would just be [the same as it is today](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/internal/spanner_stub.cc#L243). But maybe I'm not understanding the question.

Ack, I misunderstood.
