### ISSUE TITLE
internal::Visit(Transaction...) does not work with `void` results.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#306]
The implementation says:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/dffa5b5f4e74bf123301a52057a2b4914e5f5533/google/cloud/spanner/internal/transaction_impl.h#L63

When the return type is `void` that local variable definition is invalid.

**Comment by devbww** [comment]
Pending clarification on whether a `void` return type is ever needed.

**Comment by devbww** [comment]
Given that the `Transaction` visitor should "always" be running some RPC (that's what the `TransactionSelector` is for), and RPCs always have some form of result/status to return, I'll say (for now) that this is working as intended.  The future may still prove me wrong.
