### ISSUE TITLE
Implement Client::BeginTransaction.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#311]
I think we need a `Client::Begin` or `Client::BeginTransaction` function. If not, how does one create a transaction to use in multiple `Read()` and/or `ExecuteSql()` requests?

If I am wrong, just mention how the application is supposed to perform multiple queries in the same transaction, and close the bug.

**Comment by devbww** [comment]
The application should just perform the multiple queries, using the same transaction, without regard to its state.  The first operation (internally) sees a `begin` TransactionSelector, but it will be overwritten with the assigned id when the operation completes.  All subsequent operations will just see that `id` TransactionSelector.

The only time this might be problematic is when the operations are being performed in parallel and the latency of the first operation is significantly worse than a `BeginTransaction`.  In that case you indeed might want to do a `BeginTransaction` first, and then run all the other operations in parallel.  It is unclear whether that matters enough to complicate the API, but we can go there if it does.

**Comment by coryan** [comment]
Thanks. Closing.
