### ISSUE TITLE
feat: add methods to KeySet to insert multiple Keys or KeyRanges

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp-spanner#322]
Similar to std containers, add methods that either take a pair of iterators or a container that supports begin() and end() and add all such Keys or KeyRanges to the KeySet.

**Comment by devjgm** [comment]
I think this is at most a nice-to-have feature that is probably not worth adding until/unless we see some actual need for it. Until then, I think it's fine for a caller to iterate their own range and call `AddKey()` on each `Key` in the range.

We can reopen this if this feature becomes more important. Or feel free to reopen if there's more need for this than I'm thinking :-)
