### ISSUE TITLE
feat: add support to KeySetBuilder to remove Keys and/or KeyRanges

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp-spanner#323]
Support removing elements from a KeySetBuilder that were previously added.

**Comment by devjgm** [comment]
I can this of cases that might make this difficult (like removing a subrange of one that was added), so we should first discuss whether we want to support this at all.

**Comment by scotthart** [comment]
This issue was written before KeySet became a type-erased collection. I will edit it to indicate that the original intent was to provide this support for the C++ typed collection, now known as KeySetBuilder.

**Comment by devjgm** [comment]
Still, even removing a subrange from a `KeySetBulider` would be hard. It's not clear that we want to allow removing anything.
