### ISSUE TITLE
[Flake]: Integration tests timeout.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#329]
It seems like the default timeout in Bazel might be too short for the integration tests.

```
[1,543 / 1,545] 1 / 3 tests; Testing //google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test; 210s local ... (2 actions running)
[1,543 / 1,545] 1 / 3 tests; Testing //google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test; 242s local ... (2 actions running)
[1,543 / 1,545] 1 / 3 tests; Testing //google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test; 279s local ... (2 actions running)
TIMEOUT: //google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test (Summary)
      /h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp_spanner/bazel-out/k8-fastbuild/testlogs/google/cloud/spanner/integration_tests/spanner_client_database_admin_integration_test/test.log
INFO: From Testing //google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test:
==================== Test output for //google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test:
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from DatabaseAdminClient
[ RUN      ] DatabaseAdminClient.DatabaseBasicCRUD
Terminated
-- Test timed out at 2019-08-08 17:45:53 UTC --
================================================================================
```

https://source.cloud.google.com/results/invocations/59b261ac-f97d-4857-8160-e479f799823c/targets/cloud-cpp%2Fspanner%2Fdocker%2Fintegration/log

**Comment by coryan** [comment]
Just had another one:

https://source.cloud.google.com/results/invocations/62bb8b05-c490-4d73-862c-d54a494c4d66/targets

**Comment by coryan** [comment]
And another one:

https://source.cloud.google.com/results/invocations/0dbcb3f9-248b-4e2f-aab5-31be69bab31c/targets

**Comment by coryan** [comment]
I increased the timeout values to about 10x the observed maximum time (in my workstation). Not planning any more changes for now.

**Comment by coryan** [comment]
Two more this morning:

https://source.cloud.google.com/results/invocations/e0ed566e-e248-40e6-a21f-e08f0ba19ba6
https://source.cloud.google.com/results/invocations/ae932cb5-7f42-443f-899e-5cbc1f38c4c6

**Comment by coryan** [comment]
Note that those last two ran for 900s before timing out.

**Comment by coryan** [comment]
I just got this on my workstation:

```
//google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test PASSED in 516.4s
```

so it looks like 900s is indeed too short as a timeout.  Curious that I got much smaller numbers when running multiple iterations yesterday (several in parallel too!)

**Comment by coryan** [comment]
And another one, at 1500s!

https://source.cloud.google.com/results/invocations/5971c719-24ae-46c8-908a-90832776c550

**Comment by coryan** [comment]
I do not have any further ideas for this one.  The CI builds load balance across more instances now, they may not be enough or there may be other problems.

**Comment by coryan** [comment]
Sorry, just meant to clear the "assigned" bit.

**Comment by coryan** [comment]
These continue to happen, mostly in the samples now:

https://source.cloud.google.com/results/invocations/32d4b539-2f68-48a2-ac6f-7b3afcf11ffb/targets

**Comment by coryan** [comment]
And another:

https://source.cloud.google.com/results/invocations/dc08b3e3-0fae-4a0b-acdf-1d0217e42d03

**Comment by mr-salty** [comment]
A couple more in #637 

one thing I noted there was that the samples times out after ~15x their normal runtime, yet other integration tests in the same run had normal runtimes.  So, it seems like things just occasionally get "stuck" for some reason; it's not clear to me that any timeout would make them succeed.  So, we should try to find the root cause for that and possibly drop the timeout.

**Comment by coryan** [comment]
These have not happened for about 3 months.  It seems like load balancing the CI builds across multiple instances has fixed the problem.
