### ISSUE TITLE
Evaluate the choice of std::string as the representation of Value::Bytes

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp-spanner#347]
We currently have ...
```cc
class Value {
 public:
  struct Bytes {
    std::string data;
```
but the user may need their binary data in some other form, which would undoubtedly require a copy.

Observation 1: Suspicions are that most users actually consume/produce their binary data as a `std::string`.

Observation 2: One desirable property of the current `Value::Bytes` is that it is ordered just like Spanner orders BYTES (i.e., `std::string` does the right thing).

Question: How might we generalize `Value::Bytes` to avoid binding tightly to `std::string` or any other representation?

One idea is to store the binary data in its base64, on-the-wire representation, and provide mechanisms to encode/decode this from/to a variety of possible user representations.  This differs from what we do for types like TIMESTAMP and DATE, where we have chosen a canonical representation, but copying/conversion costs may be less of an issue in those cases.  Storing as base64 does raise the question of ordering, however.

**Comment by coryan** [comment]
Seems like we decided to change this per #413? Can we close this issue?

**Comment by devjgm** [comment]
yes. Good point. Closing in favor of #413
