### ISSUE TITLE
Consider: a Database class (rather than a string)

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#369]
Related to closed issue #301 

A Spanner database name includes a `project-id`, `instance-id`, and `database-id`. In RPCs it's represented as a string of the form `projects/<project-id>/instances/<instance-id>/databases/<database-id>`. Today in our APIs we generally pass around a database name as a `std::string`, and we provide a `MakeDatabaseName()` (https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/client.h#L371) helper function to turn the required 3 pieces into a string of the valid form.

My concerns with the current approach:

1. APIs which have a param like `std::string database_name` do not make it clear that the database name must have some specific string format. The documentation *might* have this information, but it will not appear in the code at the call site.

2. Every valid `database_name` string argument should have been constructed from our `MakeDatabaseName()` function, but nothing in the code enforces this because there's no strong type for this argument.

## Proposal

I think we should consider a small helper class like the following:

```cc
// File: database.h
class Database {
 public:
  Database(std::string project_id, std::string instance_id, std::string database_id);
  // Regular type: copy, assign, move, all `=default`

  // Accessors
  std::string const& project_id() const;
  // Also for instance_id and database_id

  // Returns the fully qualified database name of the form:
  // "projects/<project-id>/instances/<instance-id>/databases/<database-id>"
  std::string QualifiedName() const;

  // Maybe, because convenient, and there's a clear stringable format?
  std::ostream& operator<<(std::ostream& out, Database const& dn);

  friend bool operator==(Database const& a, Database const& b);
  friend bool operator!=(Database const& a, Database const& b);

 private:
  // 3 fields for project_id, instance_id, database_id
};
```

If we had this class, I'd propose that this should be the *only* place that project_id, instance_id, database_id are specified. That is **no** other functions should take those arguments. Instead, they should all accept an argument of type `Database`.

**Comment by coryan** [comment]
I like this, I think we should decide before Alpha because it will change the APIs.
