### ISSUE TITLE
Add  `&&` overloads from internal::WriteMutationBuilder::{Add,Emplace}Row.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#379]
To make `.Build()` easier to use consider adding `&&` overloads so uses can write:

```C++
auto mutation = InsertMutationBuilder(...).EmplaceRow(..., std::move(big_blob)).Build();
```

and they get move semantics for `big_blob`.

**Comment by devjgm** [comment]
I'm looking at the [current code](https://github.com/googleapis/google-cloud-cpp-spanner/blob/4393f0b8ab87902413e8566a8afc16b8bd40443d/google/cloud/spanner/mutations.h#L100-L130) and I'm not sure I see where we need to add more move support.

It looks like there's already a `Build() &&` method. `EmplaceRow()` takes forwarding references and forwards them to `AddRow()`, which accepts by value (so in the case of a moved `big_blog`, this will move-construct). Then the inner loop moves out of the vector into the mutation proto.

Has the issue already been fixed? If not, can someone clarify what needs to be fixed?

**Comment by coryan** [comment]
I believe this is the problem:

```C++
auto mutation = InsertMutationBuilder(..)
   .EmplaceRow(....) // this returns a InsertMutationBuilder&
   .Build() // this calls the const& overload, not the && overload, so we copy.
   ;
```

With a `&&` overload for `.EmplaceRow()` then we would get:

```C++
auto mutation = InsertMutationBuilder(..)
   .EmplaceRow(....) // this returns a InsertMutationBuilder&&
   .Build() // this calls the && overload, no copies, yay!! 
   ;
```

**Comment by devjgm** [comment]
Oh, that makes sense. Thanks for explaining.
