### ISSUE TITLE
Change `Value::Bytes` to be `Bytes<T>`

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#413]
`Value::Bytes`([link](https://github.com/googleapis/google-cloud-cpp-spanner/blob/7586d46bfcd5f5b1ccf3d6f0edc7cbcddebc3ed7/google/cloud/spanner/value.h#L194-L222)) is currently implemented to hold a single data member of type `std::string`. Instead of us choosing `std::string` as The One Preferred data type for string a sequence bytes, we probably want a more general type that can efficiently accept and return bytes stored however the user has them.

Therefore, we probably want a type that looks like:

```cc
template <typename T>
class Bytes {
 public:
  template <typename Container>
  explicit Bytes(Container const& c) {
    // base64-encodes the data in `c` into `data_`
  }

  template <typename Container>
  T get() const {
    // base64-decode's data_ into a container of type `T`
    // Can this decoding fail? Should this return StatusOr<T>?
  }

 private:
  std::string data_;
};
```

A few other thoughts:

* We probably do not want to define `operator<()`, but we *do* want equality
* This class is complicated enough that it should probably live in its own `bytes.h` file
* We can define whatever other templated constructors that we want. For example, we *migth* want a constructor that takes a start and end iterator pair. This could be done in a future PR.

**Comment by devjgm** [comment]
@devbww I can't recall. Did you say you were doing this? If so, feel free to assign yourself. If not, that's fine, I can take it.

**Comment by devbww** [comment]
> @devbww I can't recall. Did you say you were doing this?

Yes, I did, and I'm happy to.
