### ISSUE TITLE
Consider: writing a wrapper for google::spanner::v1::PartitionOptions.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#452]
This is (AFAICT) the only naked proto we expose in the non-admin APIs for the client library.  Currently here:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/87c2d3509872e539ffa8b25db6944779e27f944d/google/cloud/spanner/client_options.h#L111

(but will be moving soon).  I wonder if we should write a wrapper, as we wrap all the other proto types.

**Comment by devjgm** [comment]
I think you're right. I think we should make `PartitionOptions` its own struct and move it to its own `partition_options.h` file.
