### ISSUE TITLE
Add `x-goog-api-client` metadata for telemetry purpose

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp-spanner#462]
`x-goog-api-client` is needed for our telemetry pipeline. For BigTable client, the value of the header is constructed [here](https://github.com/googleapis/google-cloud-cpp/blob/a74734560d91b8358d29cff5a031035b00ccd5cc/google/cloud/bigtable/metadata_update_policy.cc#L46) and actually added [here](https://github.com/googleapis/google-cloud-cpp/blob/a74734560d91b8358d29cff5a031035b00ccd5cc/google/cloud/bigtable/metadata_update_policy.cc#L56)

**Comment by tmatsuo** [comment]
If the fix for #415 contains `x-goog-api-client`, yes it's a dup, but I was not sure so I created this.

**Comment by devjgm** [comment]
Moving this to Alpha, because if some users happen to use this library once it's alpha, I'd like that to show up in stats.
