### ISSUE TITLE
ensure SessionHolder does not call back into a deleted Connection

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#469]
After recent changes (#465, #461), we now have an implicit requirement that `Transaction`s must not outlive the `Connection` (Impl) that created them, since the `Transaction` now attempts to return its session to the `ConnectionImpl` when it is destroyed. *[edited: I stated this wrong initially]*

Should we document that as a requirement, or add reference-counting in the deleter to ensure it can't happen?  We could use a `weak_ptr` if we didn't want to keep the `Connection` alive just to allow returning sessions to the pool.

**Comment by devjgm** [comment]
FWIW, I think something with `weak_ptr` sounds good. I like the idea of making the issue impossible rather than documenting the requirement
