### ISSUE TITLE
transaction retry should re-use the same session

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#472]
From https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.TransactionOptions

> Retrying Aborted Transactions
> When a transaction aborts, the application can choose to retry the whole transaction again. To maximize the chances of successfully committing the retry, the client should execute the retry in the same session as the original attempt. The original session's lock priority increases with each consecutive abort, meaning that each attempt has a slightly better chance of success than the previous.

**Comment by coryan** [comment]
I think we can safely push this to Beta. There is no reason why it would change the API, and it probably just affects performance, not functionality, right?

**Comment by devbww** [comment]
My opinion has been that it might change the API, or at least change what we say about how users are supposed to mix `Client`s and `Transaction`s.  But this whole movement towards `Transaction`s owning sessions has muddied the waters there too, so I guess I'll defer.

Still, the checked-in code current reads ...
```
The lock priority of the transaction increases after each prior aborted
transaction, meaning that the next attempt has a slightly better chance
of success than before.
```
and without this behavior ("transaction retry should re-use the same session"), that is a lie.  So something should change in Alpha.
