### ISSUE TITLE
Implement spanner_batch_client example.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#478]
This example seems to use `PartitionQuery()`:

https://github.com/GoogleCloudPlatform/golang-samples/blob/40a33f7ff5de11da00a6715eaa29ce45fdf92387/spanner/spanner_snippets/snippet.go#L826-L869

**Comment by tmatsuo** [comment]
Do we have batch client?

**Comment by coryan** [comment]
> Do we have batch client?

Not a separate client, but we have  `PartitionQuery()` and `ExecuteQuery()` with a `QueryPartition`:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/3157ba421a2bf2f6513ed80cad0c4885783de4e8/google/cloud/spanner/client.h#L267-L280

https://github.com/googleapis/google-cloud-cpp-spanner/blob/3157ba421a2bf2f6513ed80cad0c4885783de4e8/google/cloud/spanner/client.h#L327-L350
