### ISSUE TITLE
Implement the spanner_create_struct_with_data example

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#481]
Show how to create a C++ data structure used as a `STRUCT<>` parameter to a query, including how to populate values into the C++ data structure:

https://github.com/GoogleCloudPlatform/golang-samples/blob/40a33f7ff5de11da00a6715eaa29ce45fdf92387/spanner/spanner_snippets/snippet.go#L696-L715

**Comment by tmatsuo** [comment]
I guess the correct link to go sample is:

https://github.com/GoogleCloudPlatform/golang-samples/blob/40a33f7ff5de11da00a6715eaa29ce45fdf92387/spanner/spanner_snippets/snippet.go#L282-L316

**Comment by tmatsuo** [comment]
I think it's already implemented:
https://github.com/googleapis/google-cloud-cpp-spanner/blob/3157ba421a2bf2f6513ed80cad0c4885783de4e8/google/cloud/spanner/samples/samples.cc#L1115-L1132

I'm closing this, but please reopen if I'm wrong.
