### ISSUE TITLE
Implement the  spanner_dml_batch_update example

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#483]
The description reads "Code sample showing how to call multiple DML SQL statements.", I cannot find code in golang, C# or Java that shows this. PHP has a way to send an array of SQL statements, so maybe it is language specific?

Created for completeness, we might decide to not implement this after all.

**Comment by devjgm** [comment]
Is this just supposed to use `ExecuteBatchDml()`: https://github.com/googleapis/google-cloud-cpp-spanner/blob/0f4392f002c59766080a628d532ac6dc09cf566f/google/cloud/spanner/client.h#L423 Or something else?

**Comment by coryan** [comment]
Judging by the (new?) code sample in golang it just just using `ExecuteBatchDml()`:

https://github.com/GoogleCloudPlatform/golang-samples/blob/5605e9f3002800e64862b445361098776401deed/spanner/spanner_snippets/snippet.go#L1256-L1278
