### ISSUE TITLE
Consider: making Value::is_null() a template

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#49]
The [spanner::Value](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/value.h) class currently has a non-templated `is_null()` method, because we do not need to know the contained value's type in order to determine if the contained value is null. That said, it might make sense to make the `is_null()` method a template so that it checks both the nullness and the type in one call. For example, we might want to consider something like the following:

```cc
class Value {
 public:
  ...
  template <typename T>
  bool is_null() const;
  ...
};
```

**Comment by devbww** [comment]
My thoughts here are that we're best off consistently treating a Value as either,

1. T(null, v1, v2, ...), or
2. null + T(v1, v2, ...),

and not something in between.  That is, either the null is typed or it is not.

The general decision tree when dealing with a value is then either:

1. is\<T\>(v)? -> !is null\<T\>(v)? -> get\<T\>(v), or
2. !is null(v)? -> is\<T\>(v)? -> get\<T\>(v).

In the first world, "is_null\<T\>(v)" is the appropriate question (and you can even ask it without an "is\<T\>(v) guard).  Sure enough, we could provide an "is_null(v)" defined as "for some T: is_null\<T\>(v)", but that seems unnecessary and confusing.  (I liken it to "is_zero(v)" defined as "for some T: is_zero\<T\>(v) == 0".)

In the second world, "v is null" implies "is<T>(v) is false" for all T.

Given that we actually have type information for null values, I would suggest that option 1 is the right choice, and therefore that the is_null predicate should be typed.
