### ISSUE TITLE
write a test that verifies Sessions are not leaked

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#506]
I reversed a comparison that led to sessions being leaked (see #505) and no existing tests caught it... we should add such a test.

**Comment by devjgm** [comment]
Given all the changes that have occurred w/ session pooling, is this issue still relevant? Or has it already been covered by some other change/test that was added?

**Comment by devjgm** [comment]
We discussed this offline. At this point, there's no actual issue that we can point to that needs to be fixed. If/when we discover a session leaking problem, or we imagine a reasonable scenario whereby sessions might be leaked, and we can detect and guard against them, then we may open a bug and fix that issue a that point.

For now, we think there's nothing to be done here.
