### ISSUE TITLE
PartialResultSetReader issues if NextValue() is never called

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#511]
If the caller doesn't read any rows from a `PartialResultSetReader` (i.e. `NextValue()` is never called), there are two issues.

- If the stats don't come in the initial Read(), then we will never read them.
- The destructor calls Finish(), but calling finish prematurely (before Read() returns false) deadlocks (per @coryan).

I think the solution to the first issue is, if the metadata doesn't contain any row fields (i.e. the response has no data), we should keep calling `Read()` until it returns false. I think there should be one additional successful `Read()` containing the stats (if applicable), followed by a `Read()` returning false. Doing this will also help with the second issue (since we'll call `Finish()` after `Read()` returns false).

Doing that should also fix the occurrences of the second issue we're seeing, except in cases where there are results and don't iterate through them all. Carlos suggested calling `TryCancel()` (that's on the context, I think?) in that case; alternatively we could keep calling `Read()` and discarding the results in the destructor. I'm a bit concerned about whether Cancelling is correct or if it can have surprising effects. Can a SQL statement both modify data and return results? In that case, would cancelling potentially undo the modifications? If so, that seems wrong to me - consuming the read data shouldn't have any effect on whether the modifications happen... or maybe it's a non-issue

**Comment by coryan** [comment]
> Carlos suggested calling `TryCancel()` (that's on the context, I think?)

Yes.

> in that case; alternatively we could keep calling `Read()` and discarding the results in the destructor.

That could take a long time. Presumably if the application returned early from a for-loop like this is:

```C++
for (auto row : reader_from_very_long_select->Rows<...>()) {
  if (...) break;
}
```

They did not intend to continue reading all the values.  At least I would not want the library to continue reading, I want my CPU back to do other stuff.

> I'm a bit concerned about whether Cancelling is correct or if it can have surprising effects. Can a SQL statement both modify data and return results?

Yes: `UPDATE Foo SET ... ; SELECT * FROM Foo`

> In that case, would cancelling potentially undo the modifications?

Maybe, but I doubt it.  You are canceling the stream, not the transaction, `Rollback()` does that.  Remember that the stream could also be terminated by a network-level reset, the server-side must be able to deal with truncated streams I would think.

> If so, that seems wrong to me - consuming the read data shouldn't have any effect on whether the modifications happen...

I think you answered your own question there.  The values returned by a `SELECT` are either consumed by an `UPDATE` or `INSERT` or are returned to the caller, but not both.

**Comment by devjgm** [comment]
Was this bug fixed by the call to `TryCancel()` added in https://github.com/googleapis/google-cloud-cpp-spanner/pull/489 ?

If not, can someone clarify what the actual bug is that this issue is referring to?

**Comment by mr-salty** [comment]
I believe this bug was actually fixed (before I filed it!) by the `TryCancel` call Carlos added in #489: https://github.com/googleapis/google-cloud-cpp-spanner/pull/489/files#diff-4d0bac7bb7ee0a497ebab40499aafd77R87

We also subsequently learned that we cannot run two semicolon-separated statements in the same RPC, so the discussion about reading and modifying is no longer relevant (even if that were supported since our API now has distinct methods for both, it would be a programming error).
