### ISSUE TITLE
[Flake]: CreateDatabase fails with UNAVAILABLE.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#512]
We just a build failure because the `CreateDatabase` operation failed, and we do not retry this operation.  Maybe we should consider `CreateDatabase` idempotent (it can only succeed the one time, right?  The second time it would fail with `kAlreadyExists` I think), **or** we could configure the tests to retry even non-idempotent operations because the database has randomly generated database_id so we know all failures are "safe".

https://source.cloud.google.com/results/invocations/eee411d8-1d59-46a5-b042-9d6a7965e31d/targets

```
================================================================
Running the integration tests Fri Aug 30 15:14:01 UTC 2019
================================================================
Loading:
Loading: 0 packages loaded
INFO: Build option --test_env has changed, discarding analysis cache.
Analyzing: 41 targets (0 packages loaded, 0 targets configured)
DEBUG: Rule 'boringssl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "93ddb1d452da9a6faf784d99bf66dd102db0aefa3ee341ff258d285732800c3f"
DEBUG: Call stack for the definition of repository 'boringssl' which is a http_archive (rule definition at /h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:110:9
 - /v/WORKSPACE:40:1
INFO: Analyzed 41 targets (0 packages loaded, 2799 targets configured).
Building: checking cached actions
INFO: Found 36 targets and 5 test targets...
[1 / 84] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[1,472 / 1,476] Testing //google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test; 0s local ... (4 actions running)
[1,472 / 1,476] Testing //google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test; 11s local ... (4 actions running)
[1,472 / 1,476] Testing //google/cloud/spanner/integration_tests:spanner_client_database_admin_integration_test; 20s local ... (4 actions running)
FAIL: //google/cloud/spanner/samples:spanner_client_samples (see /h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp_spanner/bazel-out/k8-fastbuild/testlogs/google/cloud/spanner/samples/spanner_client_samples/test.log)
INFO: From Testing //google/cloud/spanner/samples:spanner_client_samples:
==================== Test output for //google/cloud/spanner/samples:spanner_client_samples:
Running samples in database db-dbvgo_nwwsj94hqecqnij0bdysj
Running spanner_create_database sample
Error in non-idempotent operation CreateDatabase: failed to connect to all addresses [UNAVAILABLE]
external/bazel_tools/tools/test/test-setup.sh: line 323: find: command not found
================================================================================
```

**Comment by coryan** [comment]
While I think this is a problem, I do not think it should block Alpha.

**Comment by coryan** [comment]
@tmatsuo Any thoughts on this one?

**Comment by coryan** [comment]
I have a repeat of this one:

https://source.cloud.google.com/results/invocations/4ac968b6-30eb-4a0f-a176-8ebb586c3754/targets

It seems to me that (a) a failure with `UNAVAILABLE` is *not* retryable in this case, (b) the problem might be avoided if we test the `grpc::Channels` before trying to use them, maybe using `WaitForConnected()`:

https://grpc.github.io/grpc/cpp/classgrpc_1_1_channel_interface.html#a31d360cd218614814d68e01e07ce55cc

**Comment by tmatsuo** [comment]
I have few questions.

`WaitForConnected()` has deadline. What value should we use for the deadline?
Is it worth making this value configurable on the `ConnectionOptions`?
It is natural to call `WaitForConnected()` just after creating the gRPC channel. What should I do if `WaitForConnected()` returns false?

**Comment by tmatsuo** [comment]
Answering my own questions.

Maybe I can just start with a constant (200ms for example), and do nothing it it returns false.

**Comment by coryan** [comment]
We should also consider running these in the background, now that we have a completion queue to do so, and maybe the right call is this:

https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_channel.html#a26d3eb40a00bc1ab58eb0752579c12d0

**Comment by tmatsuo** [comment]
Attempted to fix with this PR:
https://github.com/googleapis/google-cloud-cpp-spanner/pull/1101

I think it's way easier to fix this flake by retrying UNAVAILABLE in tests.

**Comment by coryan** [comment]
I like that idea, but it requires introducing a policy for "what is idempotent" we did that in the storage client if you want inspiration.

**Comment by tmatsuo** [comment]
One more thought on this. According to the Spanner team, If we retry CreateXXX, these request may fail when the original request actually succeeded. In that case, user will see an error indicating there's a conflict.

How about to introduce a call option like `CREATE_RETRY_WITH_EXIST_OK`, and `DELETE_RETRY_WITH_NOT_FOUND_OK`?

**Comment by coryan** [comment]
I would prefer if we used policies to control what is retried instead of a list of enums.  That way the application developer can add their own behavior if they need to, instead of us having to think about all possible behaviors in a list of enums.

**Comment by devjgm** [comment]
Any fixes we make here should affect the API, so I don't think this needs to be a blocker for Beta. SG?

**Comment by coryan** [comment]
I believe you meant "should **not** affect the API".  If so, I agree.

**Comment by devjgm** [comment]
Note: The last repo of this was Nov 19. If we don't see this issue again before Feb 19 (~90 days), we should close this issue, as we've done with other flakes.

**Comment by coryan** [comment]
Well, we just had a repeat:

https://source.cloud.google.com/results/invocations/aefdd58a-a645-4efc-8327-88b701588aa9/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp-spanner%2Fmaster%2Fdocker%2Fasan-presubmit/log

**Comment by coryan** [comment]
Two on the same build actually:

https://source.cloud.google.com/results/invocations/2c9940fb-7ede-4ec6-8dd2-4999833c4b8d/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp-spanner%2Fmaster%2Fdocker%2Fubsan-presubmit/log

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/849862d0-7c76-4cf8-80d0-2939d9dd9231

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/636c3ce9-9388-4782-ab0f-5f8c20af84a6

**Comment by mr-salty** [comment]
https://source.cloud.google.com/results/invocations/fd32d4a1-d311-4101-8d73-ce807d7726ba

**Comment by coryan** [comment]
Note that this is similar to googleapis/google-cloud-cpp#4010, it is a problem for all libraries w.r.t. using non-idempotent operations in tests (and/or testing said operations, which is a closely related thing, but not the same).

@devjgm I think we should close this as a duplicate of the other issue, before or after this one is moved to `-cpp`.

**Comment by devjgm** [comment]
Closing now SGTM.
