### ISSUE TITLE
Implement spanner::InstanceAdminClient::UpdateInstance

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#520]
At the end of this task we will have:

- [ ] The member function in `spanner::InstanceAdminClient` and related classes.
- [ ] Some unit tests to demonstrate that failures are handled correctly, including retries.
- [ ] An integration test to demonstrate the function works against production.
- [ ] An example to link from the Doxygen documentation.

**Comment by tmatsuo** [comment]
@coryan

`UpdateInstanceRequest` has mandatory `field_mask` field, it needs to be set with paths representing fields in the `Instance` proto message. Fields declared here are updated on the server side.

Should we surface this to the user, or should we just always set the known fields automatically?

**Comment by coryan** [comment]
I see two options:

- Just expose the raw protos, let the application developer deal with it. This is Okay, but not as elegant as:
- Implement a builder to change (only) the modifiable parameters, and track which ones are set by the application, for example:

```C++
void F(spanner::InstanceAdminClient client, Instance ins) {
  client.UpdateInstance(ins,
      UpdateRequestBuilder()
           .SetDisplayName("foo")
           .SetNodeCount(7)
         .Build());
}
```

**Comment by tmatsuo** [comment]
Thanks! I'll implement the first option and try to implement the builder too.
