### ISSUE TITLE
should RunTransaction only loop on StatusCode::kAborted?

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp-spanner#529]
Consider snippets like ...
```
c.ExecuteSql(txn, ...);
```
and ...
```
RunTransaction(c, {}, [](Client c, Transaction txn) {
  c.ExecuteSql(txn, ...);
  return ...;
});
```
If the first one retries transient failures, does/should the `RunTransaction()` loop also retry transient failures?  (Is `StatusCode::kAborted` "transient"?)

Strawman: `kAborted` is a special case, handled only by `RunTransaction()`.  Indeed, let's not even call the `RunTransaction()` loop "retries", but rather "reruns".

**Comment by devjgm** [comment]
FTR, what @devbww is saying here makes sense to me.

**Comment by coryan** [comment]
For what is worth, defining a new `ReRunPolicy` that only acts on `kAborted` should be as simple as:

```C++
namespace internal {
struct TransactionReRun {
  static inline bool IsTransientFailure(StatusCode code) {
    return code == StatusCode::kAborted;
  }
}; 
}

using ReRunPolicy =
    google::cloud::internal::RetryPolicy<google::cloud::Status,
                                         internal::TransactionReRun>;

using LimitedTimeReRunPolicy =
    google::cloud::internal::LimitedTimeRetryPolicy<google::cloud::Status,
                                                    internal::TransactionReRun>;

```

Note that it is a different type from `RetryPolicy` so we could change `RunTransaction()` (or `RunCommitBlock`) to take one of these new policies without risk of confusion.
