### ISSUE TITLE
Consider: RunCommitBlock() as a replacement for RunTransaction()

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#534]
[ Note: Naming is still open. I'm using `RunCommitBlock` in this issue so that I have a vocabulary to talk about an alternative to `RunTransaction` ]

**TL;DR:** I propose that we completely replace our existing `RunTransaction()` function with:
```cc
StatusOr<CommitResult> RunCommitBlock(
    std::function<StatusOr<CommitResult>()> const& f);
```
Working version https://github.com/googleapis/google-cloud-cpp-spanner/compare/master...devjgm:run-commit?expand=1

## The problem

The `RunTransaction` ([code](https://github.com/googleapis/google-cloud-cpp-spanner/blob/b89d935dae6aaac5aa06ad1ead5868a05aa64bfa/google/cloud/spanner/client.h#L445)) function that we have today was designed in a previous iteration of this library's API back when we had a goal of *hiding* `Commit()`, `Rollback()`, and read-write transactions from the user. That is, users were able to *use* read-write transactions, but they were not able to *create* them on their own. The only way a user could get a read-write transaction was by using the `RunTransaction` function, which itself creates a read-write transaction and passes it as an argument to the user-provided functor. `RunTransaction()` would itself be responsible for creating the transaction, calling the user-provided functor, then committing the user's transaction and any optional mutations. Given these requirements, we created the following function signature:

```cc
StatusOr<CommitResult> RunTransaction(
    Client client, Transaction::ReadWriteOptions const& opts,
    std::function<StatusOr<Mutations>(Client, Transaction)> f);
```
After *using* this function a few times in tests, I think it feels awkward for the following reasons:

* The user needs to mention the `client` twice-ish: As the first argument to `RunTransaction()` itself, then the user also needs to *accept* this same client as an argument to the functor they provide. 
* The user needs to specify `ReadWriteOptions`, of which there are none. We could fix this one by adding a `RunTransaction` overload that doesn't require options.
* The user is not allowed to use the `MakeReadWriteTransaction([opts])` function that we provide them with. Instead, they are supposed to use the `txn` that we pass to their functor.
* The user's functor must return a `StatusOr<std::vector<Mutation>>`, which requires that the user's functor always speak in terms of `Mutation`s, even if the functor only executes DML which doesn't use `Mutation`. I don't think a user functor returning `return std::vector<Mutation>{};` is a clear or explicit way to indicate "Please commit this transaction".
* The user is not allowed to call `Client::Rollback()` or `Client::Commit()`, which are public functions that we give them. This is opposite of if the user is *not* using `RunTransaction`, in which case they are *required* to use `Rollback()` and `Commit()`. This is inconsistent.
* Some inputs to the user's functor are arguments, other inputs need to be lambda captures. This is inconsistent.

**I believe we ended up here by designing `RunTransaction()` for a set of different requirements.** Now that our requirements have changed (namely, we *do* expose read-write transactions to users along with `Rollback()` and `Commit()`) I believe there are further simplifications that we can and should make to our "transaction runner".

## Proposed solution: `RunCommitBlock()`

To design the alternative, I suggest we start from the simplest hello-world-style code that a user might use a read-write transaction for, and then figure out how to naturally "wrap" that in some re-runner to handle aborted commits.
```cc
auto txn = MakeReadWriteTransaction();
auto dml_result = client.ExecuteSql(txn, dml);
auto commit_result = client.Commit(dml_result);
```
This code should work (I didn't test, this, but I'd expect it to work modulo any accidental bugs). Indeed, it'll probably work fine for a while... until that Commit returns ABORTED. And so with minimal modifications to the simple code, we get the following:
```cc
auto commit_result = RunCommitBlock([&] { 
  auto txn = MakeReadWriteTransaction(); 
  auto dml_result = client.ExecuteSql(txn, dml);
  return client.Commit(txn);
});
```
The only changes necessary in this version are:
1. Wrap the "block" in a no-argument functor. Lambda capture any arguments the user wants. This is standard, vanilla C++.
2. The functor should call and return the result of `Commit()`.

The `RunCommitBlock()` function's only purpose is to call the user-provided functor, until it returns success or a non-ABORTED error. It *does not* call commit or rollback.

**Naming and vocabulary**

In this code I use the term "commit block" to refer to a section of code that starts with the creation of a read-write transaction and ends with a call to `Client::Commit()` of that transaction. Indeed, this is what all straight-line user code with a read-write transaction will look like, so this appears to be the package that we want the user-provided functor to encapsulate. Therefore, I'm using the term "Run Commit Block" for the helper function. But we could continue to use the term "RunTransaction" if we choose.

## What about rollbacks?

Consider a more complicated commit block like the following:
```cc
auto commit_result = RunCommitBlock([&]() -> StatusOr<CommitResult> {
  auto txn = MakeReadWriteTransaction();
  auto read_result = client.Read(txn, ...);
  if (!read_result) return read_result.status();  // <-- What happens to txn?
  return client.Commit(txn, GetMutations(*read_result));
});
```
If the `Read()` call fails and the functor returns early, what happens to the transaction? In the above code if the error was not ABORTED, the transaction will be leaked and the server will clean it up in [10 seconds](https://github.com/googleapis/googleapis/blob/a2158681f6e30c5fd9446eb1fd7b5021a6d48bfa/google/spanner/v1/transaction.proto#L126). This is no terrible, but it's also not super desirable.

One way to fix this is to observe that fundamentally *all read-write transactions should eventually be committed or rolled back*. So perhaps we want to change how *all* read-write transactions behave, such that their destructor rolls them back if they haven't already been rolled back or committed. Alternatively, we could create a special "`AutoRollbackTransaction`" that works exactly like a read-write transaction except that it rolls itself back if not committed. This latter option was used in [my draft PR](https://github.com/googleapis/google-cloud-cpp-spanner/compare/master...devjgm:run-commit?expand=1).

## Questions

1. Do we like the existing `RunTransaction` interface and want to keep it?
2. Do we like the `RunCommitBlock()` method presented in this issue [and in in this PR](https://github.com/googleapis/google-cloud-cpp-spanner/compare/master...devjgm:run-commit?expand=1)?
3. Should *all* read-write transactions know how to auto-rollback themselves? If not, is a separate `AutoRollbackTransaction` good?
4. (small issue) naming: Do we like "Run Commit Block"? Or do we prefer to keep "RunTransaction"? Or something else?

**Comment by devjgm** [comment]
FTR, jgm's opinions/answers to the questions:

1. No.
2. Yes.
3. Probably yes, all RW transactions should likely roll themselves back, but an `AutoRollbackTransaction` doesn't bother me too much either.
4. I think I like the `RunCommitBlock` terminology, because I think it makes it clear that we're talking about some "block" of code, and I think the "Commit" term is the most important part of what's happening and is therefore nice in the function's name. But `RunTransaction` is a fine name too if others prefer that one.

**Comment by devjgm** [comment]
We talked about this in person a bit. But I'd like to hear @coryan 's thoughts here. Happy to discuss in more detail too (or in chat or something).

**Comment by coryan** [comment]
I think this is better than what we have, and therefore we should do it. To answer your questions:

> * Do we like the existing `RunTransaction` interface and want to keep it?
No.

> * Do we like the `RunCommitBlock()` method presented in this issue [and in in this PR](https://github.com/googleapis/google-cloud-cpp-spanner/compare/master...devjgm:run-commit?expand=1)?

Mostly, see below.

> * Should _all_ read-write transactions know how to auto-rollback themselves? If not, is a separate `AutoRollbackTransaction` good?

Calling a RPC in a destructor is problematic, it can fail, how do we report failures? Not even exceptions would help us here.

> * (small issue) naming: Do we like "Run Commit Block"? Or do we prefer to keep "RunTransaction"? Or something else?

I do not have a better suggestion than `RunCommitBlock`, except maybe `RerunUntilNotAborted(...)`? Or simply `UntilNotAborted`?

My biggest issue is the return type.

Does `RunCommitBlock` need to return `CommitResult`?  If calling `Commit` is left to the application, maybe they want to return `void`? Or a user-defined type with the results or summary of some query?

So maybe this should be:

```C++
template <typename Functor>
auto RunCommitBlock(Functor&& functor) -> StatusOr<invoke_result_t<Functor>> {
  // Do stuff here, return the result from calling `functor`.
}
```

Do not block on discussing the return type, we can merge your changes and "improve" on them later (or not, if we think they are good enough).

**Comment by devjgm** [comment]
> Calling a RPC in a destructor is problematic, it can fail, how do we report failures? Not even exceptions would help us here.

You're right. In this case, the thing that might save us is that it's OK to ignore the result of `Rollback()`. If it succeeds, great. But if it fails, the server will clean up the transaction in about [10 seconds](https://github.com/googleapis/googleapis/blob/a2158681f6e30c5fd9446eb1fd7b5021a6d48bfa/google/spanner/v1/transaction.proto#L126) anyway.

> Does RunCommitBlock need to return CommitResult? If calling Commit is left to the application, maybe they want to return void? Or a user-defined type with the results or summary of some query?

Hmm, it might be nice to allow users to return their own type wrapped in a `StatusOr`. We'd still need the `StatusOr` so that `RunCommitBlock` would know when to rerun. So the user's functor must return a `StatusOr<T>`. We could of course document and enforce this with a static_assert or something.

As you say, this may be a good next improvement on `RunCommitBlock`.

**Comment by scotthart** [comment]
Here's a version that makes passing Transaction options and returning Mutations optional.
https://github.com/googleapis/google-cloud-cpp-spanner/compare/master...scotthart:transaction_runner?expand=1

**Comment by devjgm** [comment]
We discussed this at length and decided to go with a different solution. See #557 for the details.
