### ISSUE TITLE
Create example/documentation on how to persist serialized partitions.

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp-spanner#541]
Even though serialized partitions are implemented as a std::string, from the result of calling protobuf::MessageLite::SerializeToString, they likely do not behave as anticipated when attempting to write them to a file or stream.

**Comment by devjgm** [comment]
Can you say more about this, because I don't follow where or why there may be a problem?

**Comment by coryan** [comment]
Suppose you are a user, that is unfamiliar with how the code is implemented.  You need to use partitioned queries, you hear that to do that you use `ReadPartition`, then serialize the partition with

```C++
StatusOr<std::string> SerializeReadPartition(ReadPartition const& read_partition);
```

and the somehow "send" that string to a remote machine.

I ask myself [1]: "What is the format of that string?"  "Is it a NUL terminated ASCII or UTF-8 string"?  "If not, why is it not a `std::vector<std::uint8_t>`"?

Then I see that there is a helpful example showing how to use this, except that the one bit that is hard to figure out (how to persist the string so I can give it to another process) is not covered by the example. I think I am slightly annoyed at this point.


[1] And that is when I am being careful, and not being my usual self that thinks "`std::string`, must be ASCII or something, let me just save it using `operator<<`".

**Comment by devjgm** [comment]
> "What is the format of that string?" "Is it a NUL terminated ASCII or UTF-8 string"?

We can/should document that it's an opaque blob of bytes. Would that help?

> "If not, why is it not a std::vector<std::uint8_t>"?

If you think that would help, I'd be happy to change the return type to a `std::vector<std::uint8_t>`

**Comment by coryan** [comment]
> > "What is the format of that string?" "Is it a NUL terminated ASCII or UTF-8 string"?
> 
> We can/should document that it's an opaque blob of bytes. Would that help?

Yes. I think we should say something like: "Note that the `std::string` object should be treated as a blob of bytes, it may contain embedded NULs and other non-printable characters."

That at least makes it clear how this is to be treated.  I think we should also add an example, something like:

```C++
void SerializeAndExportPartitionExample(ReadPartition const& read_partition, std::ostream& os) {
  auto serialized = spanner::SerializeReadPartition(read_partition);
  if (!serialized) throw std::runtime_error(serialized.status().message());

  // Because the serialized value is a blob of bytes we have to first save its size:
  os << serialized.size() << "\n";
  // and then save the values:
  os.write(serialized.data(), serialized.size());
}
```

and then write the analogous function for reading the data back.

> > "If not, why is it not a `std::vector<std::uint8_t>`"?
> 
> If you think that would help, I'd be happy to change the return type to a `std::vector<std::uint8_t>`

That would be fine with me too, modulo it would need copying when using the protobuf serialization/deserialization functions.
