### ISSUE TITLE
Replace RunTransaction() with Client::Commit(functor)

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#557]
(See #534 for a description of some problems with the existing `RunTransaction()` function. That issue also presents an alternative design (called `RunCommitBlock`) that was discussed but we decided not to move forward with. This issue captures preferred idea to replace the existing `RunTransaction()`.)

We want to implement a "transaction runner" that is an overload of `Client::Commit`. This overload will take a user-provided functor instead of a `Transaction` and `std::vector<Mutation>`. Its interface should look like:

```cc
class Client {
 public:
  ...
  StatusOr<CommitResult> Commit(
    std::function<StatusOr<Mutations>(Transaction)> mutator);
  ...
};
```
This `Commit` overload will commit the transaction and optional mutations, along with handling rollbacks, exactly as `RunTransaction` does today. The only real changes from `RunTransaction` today are in the function's interface -- this one is much simpler for users to call.

NOTE: This overload will **replace** `RunTransaction`. That is, `RunTransaction` should be deleted.

**Comment by devbww** [comment]
For what it's worth, my test implementation looked like ...
```
StatusOr<CommitResult> Client::Commit(
    std::function<StatusOr<Mutations>(Transaction)> mutator) {
  for (;;) {
    // TODO(#472): Make this transaction use the same session each time.
    Transaction txn = MakeReadWriteTransaction();
    StatusOr<Mutations> mutations;
#if GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS
    try {
#endif
      mutations = mutator(txn);
#if GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS
    } catch (...) {
      auto status = Rollback(txn);
      if (!status.ok()) {
        GCP_LOG(WARNING) << "Rollback() failure in Client::Commit(): "
                         << status.message();
      }
      throw;
    }
#endif
    if (mutations) {
      auto result = Commit(txn, *mutations);
      if (result || result.status().code() != StatusCode::kAborted) {
        return result;
      }
    } else if (mutations.status().code() != StatusCode::kAborted) {
      auto status = Rollback(txn);
      if (!status.ok()) {
        GCP_LOG(WARNING) << "Rollback() failure in Client::Commit(): "
                         << status.message();
      }
      return mutations.status();
    }
    // kAborted:
    // if (looping-too-long) return Status(kWhat, "why");
  }
}
```
