### ISSUE TITLE
Consider: Taking a dep on Abseil

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#566]
We are reimplementing several utilities that Abseil provides, such as optional, Status (soon?), StatusOr (soon?), make_unique, etc. Rather than making our own shared repo of utility code, it would be nice to use Abseil.

We should figure out exactly what we need form Abseil in order for us to take that dep. Then we should file those as Issues against Abseil so we (both projects) and prioritize them appropriately.

**Comment by coryan** [comment]
This is related to googleapis/google-cloud-cpp#2309.

**Comment by JustinBeckwith** [comment]
@devjgm while there's no hard rule, we're trying to keep only a single `type` on issues.  We're also trying to reserve `question` for customer generated questions about how the product work.  Just trying to do a little house cleaning :)

**Comment by devjgm** [comment]
Closing this. We already have at least one issue about this in -cpp.
