### ISSUE TITLE
Refactor internal::PaginationRange to google-cloud-cpp.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#567]
There is a similar (but not identical) class in google-cloud-cpp, unfortunately the differences make it a bit of a yak shaving exercise to merge both classes.

Basically the response classes in google-cloud-cpp all have the same name member *variable* with the page of results.  It is called `items` and of type `std::vector<T>`.  The protos use different names, and they are typically `google::protobuf::RepeatedFieldPtr<T>`.

I think refactoring is possible, but may require larger changes to `google-cloud-cpp` first.

**Comment by coryan** [comment]
@mr-salty I think you fixed this?

**Comment by mr-salty** [comment]
It was @devjgm in #1278 but definitely closed.
