### ISSUE TITLE
[Flake]: Windows integration tests fail if run in parallel.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#573]
I forgot about this:  grpc/grpc#16872

We cannot run the integration tests in parallel on Windows because of that bug, we just one such failure:

https://source.cloud.google.com/results/invocations/990b3e97-c90f-4722-97e2-d8784e6986d4/targets

We should run the tests serially.

**Comment by coryan** [comment]
Fixed in #578.

**Comment by coryan** [comment]
It seems that the fix did not work:

https://source.cloud.google.com/results/invocations/55a6e5d3-7dcb-409f-beaa-9790c55a5069/targets

**Comment by coryan** [comment]
And another one:

https://source.cloud.google.com/results/invocations/6ce70af6-30dc-465f-a3a3-633ef875bc87/targets

**Comment by tmatsuo** [comment]
https://source.cloud.google.com/results/invocations/6ce70af6-30dc-465f-a3a3-633ef875bc87/targets

**Comment by tmatsuo** [comment]
Oh sorry I pasted the same thing

**Comment by coryan** [comment]
And another one:

https://source.cloud.google.com/results/invocations/e5c1d129-e0cb-4ec1-abe6-1ad63f98f7b8

**Comment by tmatsuo** [comment]
Another one:
https://source.cloud.google.com/results/invocations/4eb9bd16-0c8d-4928-9fc0-c4070c972859/targets

**Comment by tmatsuo** [comment]
Another one:
https://source.cloud.google.com/results/invocations/c0e08b88-1fb2-4b0d-8b34-361cd8ad105a/targets

**Comment by coryan** [comment]
Another repeat: 

https://source.cloud.google.com/results/invocations/e727b8c9-c66f-4a50-8342-1adc2e0cfbc5

**Comment by coryan** [comment]
I am not actively working on this.  I think grpc/grpc#20565 may help with this, but it is a few weeks before that PR gets included in a release.

**Comment by coryan** [comment]
FWIW, gRPC-1.26.0 (which includes the fix referenced above) is released and it is (now) the version included with vcpkg, meaning that at least our CMake-based builds may be executed in parallel.

**Comment by devbww** [comment]
@coryan  ... do we think this is fixed now?  (This issue went out of SLO yesterday.)  Thanks.

**Comment by coryan** [comment]
I am going to say yes.
