### ISSUE TITLE
Move PartitionOptions to its own file and its own struct

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#599]
Currently `PartitionOptions` is an alias for a protobuf. We should probably make it its own struct and put it in its own file.

https://github.com/googleapis/google-cloud-cpp-spanner/blob/3274810e26a2b39b456b5391933463ad00c00150/google/cloud/spanner/read_options.h#L52

**Comment by coryan** [comment]
related: #452

**Comment by devjgm** [comment]
I didn't realize this was already filed. Closing this in favor of #452.
