### ISSUE TITLE
[Flake]: examples fail with aborted transaction

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#616]
One of the examples explicitly does not run as part of a `RunTransaction()` loop. From time to time it fails with "aborted".

https://source.cloud.google.com/results/invocations/db050d11-ae96-46d5-84ed-49cdb5f9a272/targets

```
Running spanner_read_write_transaction sample
Transaction was aborted.
```

**Comment by tmatsuo** [comment]
https://source.cloud.google.com/results/invocations/2e24cac7-138f-4af9-ae6f-d251ec73925b/log

**Comment by devjgm** [comment]
I assume we're talking about this sample:
https://github.com/googleapis/google-cloud-cpp-spanner/blob/266d526b4ee602488bda8a6c1ddd1167327e2e58/google/cloud/spanner/samples/samples.cc#L553

If so, Q: Why does this explicitly not use `RunTransaction()`?
