### ISSUE TITLE
Consider: Replacing ExecuteSql() with ExecuteQuery() and ExecuteDml()

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-spanner#629]
Today we expose `Client::ExecuteSql`[1],  which returns a `StatusOr<ResultSet>`. This makes a lot of sense when a query is issued and the caller wants to consume the resulting rows, but it makes less sense when a DML statement is issued and therefore no rows will be returned. Another difference between a "query" and a dml statement is that the dml statement will return stats about how many rows were modified.

I think we should consider removing `Client::ExecuteSql` and replacing it with two separate functions that are named for "queries" (i.e., `SELECT ...`) and DML (e.g., `INSERT ...`). The functions would exist solely so they can have a different return type that is optimized for each use case.

For *example* (this is just an example, not a formal design spec):

```cc
class Client {
 public:
  struct QueryResult {
    template <typename... Ts>
    RowParser<Ts...> Rows();
  };
  QueryResult ExecuteQuery(SqlStatement);

  struct DmlResult {
    std::int64_t row_count();
  };
  StatusOr<DmlResult> ExecutDml(SqlStatement);
};
```

Notice how `ExecuteQuery` returns `QueryResult` that is *not* wrapped in a `StatusOr`? This is because the `StatusOr` is already exposed via the `RowParser`. However, `ExecuteDml` *does* return its results wrapped in a `StatusOr`, because it needs to.

NOTE: These functions would **not** parse the given `SqlStatement` and attempt to validate that, say, `ExecuteQuery` is only given a `SELECT` statement. It would be up to the caller to use these functions correctly.

Related to #628 
Related to #217 

[1]: https://github.com/googleapis/google-cloud-cpp-spanner/blob/970ce7a559fe1fdbc7fd6435835f0dd6b889aaac/google/cloud/spanner/client.h#L243

**Comment by scotthart** [comment]
Looking at the C#, go, Java, and Python libraries, they all have different return types for DML statements vs. Query statements, so I think we would be following an established paradigm.

I agree that we should replace ExecuteSql with ExecuteQuery and ExecuteDml. If we later need to support some kind of hybrid, we could reintroduce ExecuteSql at that time. Furthermore, I think we need separate return types for each of Read, ExecuteQuery, and ExecuteDml.
