### ISSUE TITLE
ubsan flakes due to TIMEOUT running samples

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#637]
The ubsan build failed twice this afternoon with a timeout running `spanner_client_samples`:

`//google/cloud/spanner/samples:spanner_client_samples                   TIMEOUT in 915.0s`

normally this seems to take ~60s... and in the failing runs the runtimes for the other integration tests look pretty normal

**Comment by coryan** [comment]
Seems like a dup of #329 (though arguably I overloaded that poor issue with too much stuff).

**Comment by mr-salty** [comment]
Yeah, I think it's a dup...
