### ISSUE TITLE
Add && overload for Instance::FullName and Database::FullName.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#639]
Some of the code can discard the instance and database once they get the full name, seems like a waste to copy in those cases.

**Comment by devjgm** [comment]
Since https://github.com/googleapis/google-cloud-cpp-spanner/pull/652, these classes no longer store the full_name as a member, so moving out of that member wouldn't be very beneficial. Instead, they compute the `FullName()` only when asked. So I think this issue is no longer applicable.
