### ISSUE TITLE
Add retry/resume to internal::ConnectionImpl::Read(ReadPartition)

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#641]
We need to:

- [ ] Implement the functionality.
- [ ] Write a unit test verifying that it tolerates at least one transient error.
- [ ] Write a unit test verifying that it stops on the first permanent error.
- [ ] Write a unit test verifying that it stops when there are too many transient failures.

**Comment by coryan** [comment]
I believe this is blocked by #271.

**Comment by scotthart** [comment]
Client::Read(ReadPartition) creates a ReadParams from the ReadPartition and calls internal::ConnectionImpl::Read(ReadParams) which already handles retrying and resuming.

**Comment by coryan** [comment]
Shouldn't we have unit tests in case we refactor this code differently in the future?

**Comment by coryan** [comment]
I was confused, the tests already exist for `internal::ConnectionImpl`.
