### ISSUE TITLE
Add retry loop for internal::ConnectionImpl::ExecuteSql

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#643]
We need to:

- [ ] Implement the functionality.
- [ ] Write a unit test verifying that it tolerates at least one transient error when idempotent.
- [ ] Write a unit test verifying that it stops on the first transient error if not idempotent.
- [ ] Write a unit test verifying that it stops on the first permanent error.
- [ ] Write a unit test verifying that it stops when there are too many transient failures.

**Comment by coryan** [comment]
This is probably blocked by #271.

**Comment by scotthart** [comment]
Fixed in #927
