### ISSUE TITLE
Consider using symbol visibility to enforce the "API" boundary

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#675]
Making the symbols in `google::cloud::*::internal` hidden, or *only* marking the symbols outside that namespace visible (and defaulting to hidden), can make the interface boundaries more explicit, and would actually enforce them for shared objects.

There are some downsides:

- It has no effect for static libraries, so at least some users would be free to use the hidden symbols anyway.
- It requires us to add decorators (like `FOO_EXPORT`) before each class (including template classes) and function.

**Comment by devjgm** [comment]
Another downside:

* I believe these exports would also need to be applied to *internal* helper functions and templates that are used by public `inline` things. So the use of `FOO_EXPORT` would still not cleanly demarcate our actual user-facing API boundary.

My opinion is that I see little value in us manually maintaining the set of symbols that we explicitly export. That seems like it could grow to be a PITA over time.

**Comment by coryan** [comment]
FTR: I am Okay with closing this as "We thought about it, won't do it." or pushing it to GA (I do not think it changes any API).

**Comment by devjgm** [comment]
We talked about this offline and think it's probably best to close/drop this for now. Can reopen if we have new evidence about why this is needed.
