### ISSUE TITLE
[Flake]: Integration test fails with "Duplicate name in schema" error.

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp-spanner#679]
I encountered a new pattern of failure.

https://source.cloud.google.com/results/invocations/b56dc962-62ed-41a2-b5de-a463337883da/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp-spanner%2Fwindows%2Fcmake-presubmit/log
```
[----------] 1 test from DatabaseAdminClient
[ RUN      ] DatabaseAdminClient.DatabaseBasicCRUD
..\..\..\..\..\..\google\cloud\spanner\integration_tests\database_admin_integration_test.cc(134): error: Value of: metadata
Expected: is OK
Actual: Duplicate name in schema: Singers. [FAILED_PRECONDITION]
[  FAILED  ] DatabaseAdminClient.DatabaseBasicCRUD (42436 ms)
```

**Comment by coryan** [comment]
Hmm....  It looks as-if `UpdateDatabase()` was executed twice, but the retry loop for it says "not idempotent", it should not try again.

**Comment by tmatsuo** [comment]
or, did `RandomDatabaseName()` return the same name for different tests? How possible it is?

**Comment by coryan** [comment]
> or, did `RandomDatabaseName()` return the same name for different tests? How possible it is?

Anything is possible.  If we get zero entropy out of `/dev/urandom` (or RDRAND depending on the implementation of `std::random_device).  The code to initialize the PRNG is here:

https://github.com/coryan/google-cloud-cpp-common/blob/00f1310b565c581b0d59a613579ed883f45ac0dc/google/cloud/internal/random.h#L36-L70

**Comment by tmatsuo** [comment]
Ah, but in this particular case, if database names conflict, I think we would see a different error, probably `kAlreadyExists` upon database creation.

**Comment by coryan** [comment]
Yes, I wonder if the problem was that the instance was not ready.  Maybe one of us (most likely me) was creating or deleting an instance and the random instance picker chose that instance to run this test?

I think we should wait until the next bug scrub and if this does not repeat we can close it.

**Comment by coryan** [comment]
No repeats for 90 days. Closing.
