### ISSUE TITLE
consider implementing a BatchClient analog for C++

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#688]
Java has a BatchClient ([class](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClient.java)) ([sample](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/spanner/cloud-client/src/main/java/com/example/spanner/BatchSample.java)) used to coordinate passing partitioned query information between machines. Investigate implementing this for C++ (I believe we already have a similar mechanism but more commonality with Java may be a feature).

**Comment by devjgm** [comment]
We already support partitioned queries with our existing `Client` class, so I don't think we're missing any functionality. I don't think a separate "BatchClient" fits in well with the C++ library's current design.  Therefore, I think we should stick with what we have and not implement a C++ BatchClient. I think it's fine that the C++ and other libraries different in a number of ways, including in this way.

Any objections, or further reasons why a BatchClient would improve the C++ library?

**Comment by mr-salty** [comment]
I think it's still worth investigating.  `BatchClient` is a helper to facilitate executing batch transactions. - it gives the user a nicer interface [(sample)](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/5b76db818f087e8f6c15afa0347920b1a1382df9/spanner/cloud-client/src/main/java/com/example/spanner/BatchSample.java#L87-L99) that hides some of the implementation details like partition tokens that they don't really care about.

There's really a whole set of support classes - like [`BatchReadOnlyTransaction`](https://github.com/googleapis/java-spanner/blob/d8b6438aa3b881c1c9baff584a74813664be4df8/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchReadOnlyTransaction.java#L23-L39) which also claims to be usable across machines although I didn't dig into how that works exactly.

---
FYI I see the `BatchClient` class has changed repos to [here](https://github.com/googleapis/java-spanner/blob/d8b6438aa3b881c1c9baff584a74813664be4df8/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClient.java) - I should have used a permalink the first time.

**Comment by devjgm** [comment]
> I think it's still worth investigating. `BatchClient` is a helper to facilitate executing batch transactions. - it gives the user a nicer interface [(sample)](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/5b76db818f087e8f6c15afa0347920b1a1382df9/spanner/cloud-client/src/main/java/com/example/spanner/BatchSample.java#L87-L99) that hides some of the implementation details like partition tokens that they don't really care about.

We already hide partition_tokens from callers behind a nice `ReadPartition` or `QueryPartition` interface. Example:
https://github.com/googleapis/google-cloud-cpp-spanner/blob/20e2f9b011e3747fe5a8b8dc284245c11ff354b6/google/cloud/spanner/samples/samples.cc#L948-L961

That looks pretty similar to the Java sample that you linked to. Aside from language differences, I don't see an improvement in the Java case.... but maybe I'm misunderstanding the Java code.

**Comment by mr-salty** [comment]
ok, that does look somewhat similar - if so, the only reason to consider a change is more commonality than java (and other languages - for instance via misclick I discovered Ruby [does something similar](https://googleapis.dev/ruby/google-cloud-spanner/v1.14.0/Google/Cloud/Spanner/BatchClient.html))... which may be a non-goal.

**Comment by devjgm** [comment]
Since the C++ library is not missing any functionality in this regard, and the way the C++ library exposes partitioned reads/queries fits in nicely with its API, I see no reason to adopt the Java/Ruby naming. 

I'd even argue that Java's naming choice is confusing on this point: "Batch" seems like exactly the wrong word when dealing with "Partitions". "Batch" implies doing many individual things at once (e.g., "BatchDml": Many separate DML statements in one call). That's nearly opposite of "Partition", which implies doing one thing in many smaller parts.

I'm just not seeing any advantage or value in Java's naming or design in this case. But please let me know if/what I'm missing.

**Comment by coryan** [comment]
Closing, we did consider it, and decided against it.
