### ISSUE TITLE
Resolve use of `single_use_transaction` in `Commit`

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#689]
Currently, our `Commit` implementation (in `internal/connection_impl.cc`) handles a transaction that has not been started (i.e. `Commit()` was the first method called using that `Transaction`) by using the `single_use_transaction` field in `CommitRequest`. This makes the operation non-idempotent (see the comment at the end, from the proto definition).

That behavior seems questionable and surprising to me, and I think we should re-evaluate it. I think it's surprising enough on its own, if `Commit` is the only call you make inside of a `RunTransaction` functor.  it also means if you were calling `ExecuteSql` followed by `Commit` (again inside a `RunTransaction` functor) and remove the former call (or add one if it didn't already exist), you've changed the semantics of the `Commit` call substantially.

I propose our `CommitImpl` should explicitly call `BeginTransaction`, and then `Commit`, potentially retrying either of them, or re-running the entire transaction (meaning, those two operations). Also note that Session Pooling may eliminate this situation to begin with (the recommendation is to "prepare" read-write sessions by preemptively calling `BeginTransaction` on them).

If the user wants the non-idempotent `single_use_transaction` behavior, we should add another `Commit` overload that takes `ReadWriteOptions`. I assume this exists because there is some performance benefit to it, but it does not seem like the right default behavior.

See also #627 

---
comment from `CommitRequest::single_use_transaction`:

    // Execute mutations in a temporary transaction. Note that unlike
    // commit of a previously-started transaction, commit with a
    // temporary transaction is non-idempotent. That is, if the
    // `CommitRequest` is sent to Cloud Spanner more than once (for
    // instance, due to retries in the application, or in the
    // transport library), it is possible that the mutations are
    // executed more than once. If this is undesirable, use
    // [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction] and
    // [Commit][google.spanner.v1.Spanner.Commit] instead.

**Comment by mr-salty** [comment]
I think this is an aside/footnote, but something to keep in mind:

Note that the current code also sets `single_use_transaction` in the case where `Commit` is passed a single-use transaction. This is confusing because the two things aren't actually related despite both being called "single use".  In fact, a `Commit` call to the backend where [`TransactionSelector::single_use`](https://github.com/googleapis/googleapis/blob/7d388543c62ae0a94ff1598c36d804a0c417c86d/google/spanner/v1/transaction.proto#L448) is set is likely destined to fail because this type of single-use transaction is implicitly read-only and you cannot `Commit` a read-only transaction.  (although, it might be interesting to see what happens if you made such a call with `TransactionOptions::ReadWrite` set - despite the documentation referring to "single-use read-only" transactions in many places it's not as explicit as I'd like... although our current library has no mechanism to create such a `Transaction`)

**Comment by coryan** [comment]
I think this is related. I got the following error in one of my benchmarks:

```
# Error: Error in non-idempotent operation CommitImpl: Socket closed [UNAVAILABLE] [UNAVAILABLE]
```

The code is in a branch, but basically looks like this:

```C++
int RunTask(Config const& config, cloud_spanner::Client client,
            RandomKeyGenerator const& key_generator) {
  int count = 0;
  std::string value(1024, 'A');
  google::cloud::Status error;
  for (auto start = std::chrono::steady_clock::now(),
            deadline = start + config.iteration_duration;
       start < deadline; start = std::chrono::steady_clock::now()) {
    auto key = key_generator();
    auto m = cloud_spanner::MakeInsertOrUpdateMutation(
        "KeyValue", {"Key", "Data"}, key, value);
    auto result = client.Commit([&m](cloud_spanner::Transaction const&) {
      return cloud_spanner::Mutations{m};
    });
    if (!result) {
      error = std::move(result).status();
    }
    ++count;
  }
  if (!error.ok()) {
    std::cerr << "# Error: " << error << "\n";
  }
  return count;
}
```

**Comment by mr-salty** [comment]
FYI java has a method [writeAtMostOnce](https://github.com/googleapis/google-cloud-java/blob/ac6b4b6671decae180ba7cc735dd292a59789dd7/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java#L55-L84) that does the non-idempotent version of `Commit` (as I proposed in the original comment). Sounds like it does retry, based on the name and comment.

**Comment by devjgm** [comment]
Note: we may need/want a block similar to this:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/c9e36aec2740bd1878459544e2adcf30d9074479/google/cloud/spanner/internal/connection_impl.cc#L650-L666
