### ISSUE TITLE
Properly handle Session NOT_FOUND

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#914]
@coryan reported that one of his tests failed with the following error:

`Exception caught in HTTP handler: Permanent failure in RunTransactionWithPolicies: Session not found: <XXX> [NOT FOUND]`

We should handle this error internally and avoid exposing it to the user.  From https://cloud.google.com/spanner/docs/sessions

```
Attempts to use a deleted session result in NOT_FOUND. If you encounter this error, create and use a new session, add the new session to the cache, and remove the deleted session from the cache.
``` 

However, I'm not entirely sure how to accomplish this given that a `Transaction` is bound to a `Session`.  For RW transactions using `RunTransaction` we should be able to treat it similarly to an `ABORTED` and retry the whole transaction with a new session.

For RO transactions or non-idempotent mutations, it's less clear what we should do. The page linked-to above gives some general advice, but nothing specifically about this case.

**Comment by mr-salty** [comment]
Carlos also noted that NOT_FOUND could apply to other parts of the request (database, table, etc.), so we may need to perform a `GetSession` to determine the actual issue. If it's a problem with the request itself, that should be returned to the user; `Session` related errors should be handled internally.

**Comment by coryan** [comment]
Also, when we get this error we should remove the session from the pool.  Otherwise the next request to use that session will get the same error.

**Comment by devbww** [comment]
Note that the message above ...
```
Permanent failure in RunTransactionWithPolicies: Session not found: <XXX> [NOT FOUND]
```
says `Session not found`, so you may be able to distinguish failures without resorting to `GetSession()`.

**Comment by devjgm** [comment]
Note: the java library inspects the error message string to determine of the NOT_FOUND means "session not found". See here: https://github.com/googleapis/google-cloud-java/blob/2c109fc8a6462e6e0dc61b5503c2b64902f55383/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java#L1192
