### ISSUE TITLE
Consider implementing CreateInstanceRequestBuilder

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp-spanner#931]
The functions [`InstanceAdminClient::CreateInstance`](https://googleapis.dev/cpp/google-cloud-spanner/master/classgoogle_1_1cloud_1_1spanner_1_1v0_1_1InstanceAdminClient.html#ab97880cec5264ebaf3ce26f85d9dd61b) and [`InstanceAdminClient::UpdateInstance`](https://googleapis.dev/cpp/google-cloud-spanner/master/classgoogle_1_1cloud_1_1spanner_1_1v0_1_1InstanceAdminClient.html#af4dbf95901e8d5f1057409e6fc021a28) look very different because one has lots of function parameters, and the other has just one, `UpdateInstanceRequest` proto message, with a help from `UpdateInstanceRequestBuilder`.

Should we also surface `CreateInstanceRequest` on `InstanceAdminClient::CreateInstance` and provide a builder for it?

I'm on the fence. I'd like to hear opinions.

**Comment by coryan** [comment]
> Should we also surface `CreateInstanceRequest` on `InstanceAdminClient::CreateInstance` and provide a builder for it?

I think we should. The code is much cleaner (and future proof) with the builder.
